<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-PT" xml:lang="pt-PT"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; HL7 v2 — Modelo de Mensagens e Limitações – Informática Médica</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../referencias.html" rel="next">
<link href="../capitulos/cap05.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de84f8d6bb715db06a919283c2d1e787.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-9a023c9ade86a60361e96e3e3f11bc54.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-61bc4ac84974e0785b3107ee93e74bfb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-bc9f1d3aef906c45e091843ae87821a0.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../assets/css/custom.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../capitulos/cap06.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">HL7 v2 — Modelo de Mensagens e Limitações</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Informática Médica</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo escuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefácio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Fundamentos da Informática Médica</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Sistemas de Informação Hospitalares e Registos Electrónicos de Saúde</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Terminologias e Interoperabilidade Semântica</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">DICOM como Data Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Serviços DICOM e Arquitectura PACS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap06.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">HL7 v2 — Modelo de Mensagens e Limitações</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../referencias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referências</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#sec-hl7v2-modelo" id="toc-sec-hl7v2-modelo" class="nav-link active" data-scroll-target="#sec-hl7v2-modelo"><span class="header-section-number">6.1</span> O HL7 v2 e o Modelo de Mensagens</a>
  <ul class="collapse">
  <li><a href="#o-problema-que-o-hl7-v2-resolveu" id="toc-o-problema-que-o-hl7-v2-resolveu" class="nav-link" data-scroll-target="#o-problema-que-o-hl7-v2-resolveu"><span class="header-section-number">6.1.1</span> O problema que o HL7 v2 resolveu</a></li>
  <li><a href="#uma-norma-com-35-anos-de-longevidade" id="toc-uma-norma-com-35-anos-de-longevidade" class="nav-link" data-scroll-target="#uma-norma-com-35-anos-de-longevidade"><span class="header-section-number">6.1.2</span> Uma norma com 35 anos de longevidade</a></li>
  <li><a href="#o-modelo-trigger-event" id="toc-o-modelo-trigger-event" class="nav-link" data-scroll-target="#o-modelo-trigger-event"><span class="header-section-number">6.1.3</span> O modelo trigger-event</a></li>
  <li><a href="#tipos-de-mensagem-e-códigos-de-trigger" id="toc-tipos-de-mensagem-e-códigos-de-trigger" class="nav-link" data-scroll-target="#tipos-de-mensagem-e-códigos-de-trigger"><span class="header-section-number">6.1.4</span> Tipos de mensagem e códigos de trigger</a></li>
  </ul></li>
  <li><a href="#sec-hl7v2-estrutura" id="toc-sec-hl7v2-estrutura" class="nav-link" data-scroll-target="#sec-hl7v2-estrutura"><span class="header-section-number">6.2</span> Estrutura de uma Mensagem HL7 v2</a>
  <ul class="collapse">
  <li><a href="#hierarquia-de-cinco-níveis" id="toc-hierarquia-de-cinco-níveis" class="nav-link" data-scroll-target="#hierarquia-de-cinco-níveis"><span class="header-section-number">6.2.1</span> Hierarquia de cinco níveis</a></li>
  <li><a href="#os-delimitadores" id="toc-os-delimitadores" class="nav-link" data-scroll-target="#os-delimitadores"><span class="header-section-number">6.2.2</span> Os delimitadores</a></li>
  <li><a href="#segmentos-a-unidade-lógica" id="toc-segmentos-a-unidade-lógica" class="nav-link" data-scroll-target="#segmentos-a-unidade-lógica"><span class="header-section-number">6.2.3</span> Segmentos: a unidade lógica</a></li>
  <li><a href="#campos-posicionalidade-e-estados-de-preenchimento" id="toc-campos-posicionalidade-e-estados-de-preenchimento" class="nav-link" data-scroll-target="#campos-posicionalidade-e-estados-de-preenchimento"><span class="header-section-number">6.2.4</span> Campos: posicionalidade e estados de preenchimento</a></li>
  </ul></li>
  <li><a href="#sec-hl7v2-segmentos" id="toc-sec-hl7v2-segmentos" class="nav-link" data-scroll-target="#sec-hl7v2-segmentos"><span class="header-section-number">6.3</span> Segmentos Essenciais</a>
  <ul class="collapse">
  <li><a href="#msh-cabeçalho-da-mensagem" id="toc-msh-cabeçalho-da-mensagem" class="nav-link" data-scroll-target="#msh-cabeçalho-da-mensagem"><span class="header-section-number">6.3.1</span> MSH — Cabeçalho da mensagem</a></li>
  <li><a href="#evn-tipo-de-evento" id="toc-evn-tipo-de-evento" class="nav-link" data-scroll-target="#evn-tipo-de-evento"><span class="header-section-number">6.3.2</span> EVN — Tipo de evento</a></li>
  <li><a href="#pid-identificação-do-doente" id="toc-pid-identificação-do-doente" class="nav-link" data-scroll-target="#pid-identificação-do-doente"><span class="header-section-number">6.3.3</span> PID — Identificação do doente</a></li>
  <li><a href="#pv1-visita-do-doente" id="toc-pv1-visita-do-doente" class="nav-link" data-scroll-target="#pv1-visita-do-doente"><span class="header-section-number">6.3.4</span> PV1 — Visita do doente</a></li>
  </ul></li>
  <li><a href="#sec-hl7v2-ack" id="toc-sec-hl7v2-ack" class="nav-link" data-scroll-target="#sec-hl7v2-ack"><span class="header-section-number">6.4</span> Confirmação de Mensagens: o ACK</a></li>
  <li><a href="#sec-hl7v2-adt" id="toc-sec-hl7v2-adt" class="nav-link" data-scroll-target="#sec-hl7v2-adt"><span class="header-section-number">6.5</span> Mensagens ADT: o Percurso Administrativo do Doente</a>
  <ul class="collapse">
  <li><a href="#adta01-internamento" id="toc-adta01-internamento" class="nav-link" data-scroll-target="#adta01-internamento"><span class="header-section-number">6.5.1</span> ADT^A01 — Internamento</a></li>
  <li><a href="#adta02-transferência" id="toc-adta02-transferência" class="nav-link" data-scroll-target="#adta02-transferência"><span class="header-section-number">6.5.2</span> ADT^A02 — Transferência</a></li>
  <li><a href="#adta03-alta" id="toc-adta03-alta" class="nav-link" data-scroll-target="#adta03-alta"><span class="header-section-number">6.5.3</span> ADT^A03 — Alta</a></li>
  </ul></li>
  <li><a href="#sec-hl7v2-limitacoes" id="toc-sec-hl7v2-limitacoes" class="nav-link" data-scroll-target="#sec-hl7v2-limitacoes"><span class="header-section-number">6.6</span> Limitações do HL7 v2</a>
  <ul class="collapse">
  <li><a href="#fragilidade-estrutural-ausência-de-schema-formal" id="toc-fragilidade-estrutural-ausência-de-schema-formal" class="nav-link" data-scroll-target="#fragilidade-estrutural-ausência-de-schema-formal"><span class="header-section-number">6.6.1</span> Fragilidade estrutural: ausência de schema formal</a></li>
  <li><a href="#semântica-fraca-tabelas-de-valores-locais" id="toc-semântica-fraca-tabelas-de-valores-locais" class="nav-link" data-scroll-target="#semântica-fraca-tabelas-de-valores-locais"><span class="header-section-number">6.6.2</span> Semântica fraca: tabelas de valores locais</a></li>
  <li><a href="#z-segments-extensões-privadas" id="toc-z-segments-extensões-privadas" class="nav-link" data-scroll-target="#z-segments-extensões-privadas"><span class="header-section-number">6.6.3</span> Z-segments: extensões privadas</a></li>
  <li><a href="#parsing-complexidade-oculta" id="toc-parsing-complexidade-oculta" class="nav-link" data-scroll-target="#parsing-complexidade-oculta"><span class="header-section-number">6.6.4</span> Parsing: complexidade oculta</a></li>
  <li><a href="#o-integration-engine-a-peça-obrigatória" id="toc-o-integration-engine-a-peça-obrigatória" class="nav-link" data-scroll-target="#o-integration-engine-a-peça-obrigatória"><span class="header-section-number">6.6.5</span> O integration engine: a peça obrigatória</a></li>
  <li><a href="#balanço-o-que-o-hl7-v2-resolveu-e-onde-ficou-aquém" id="toc-balanço-o-que-o-hl7-v2-resolveu-e-onde-ficou-aquém" class="nav-link" data-scroll-target="#balanço-o-que-o-hl7-v2-resolveu-e-onde-ficou-aquém"><span class="header-section-number">6.6.6</span> Balanço: o que o HL7 v2 resolveu e onde ficou aquém</a></li>
  </ul></li>
  <li><a href="#sec-hl7v2-sintese" id="toc-sec-hl7v2-sintese" class="nav-link" data-scroll-target="#sec-hl7v2-sintese"><span class="header-section-number">6.7</span> Síntese e Exercícios</a>
  <ul class="collapse">
  <li><a href="#exercícios-de-consolidação" id="toc-exercícios-de-consolidação" class="nav-link" data-scroll-target="#exercícios-de-consolidação">Exercícios de consolidação</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">HL7 v2 — Modelo de Mensagens e Limitações</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-hl7v2-modelo" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="sec-hl7v2-modelo"><span class="header-section-number">6.1</span> O HL7 v2 e o Modelo de Mensagens</h2>
<section id="o-problema-que-o-hl7-v2-resolveu" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="o-problema-que-o-hl7-v2-resolveu"><span class="header-section-number">6.1.1</span> O problema que o HL7 v2 resolveu</h3>
<p>Antes do HL7, cada sistema de informação hospitalar funcionava como um silo isolado. A troca de dados clínicos entre sistemas — por exemplo, entre o sistema de admissões e o laboratório — exigia intervenção manual ou soluções proprietárias construídas caso a caso. O <strong>HL7 v2</strong> surgiu como resposta a este problema: um protocolo de camada de aplicação (camada 7 do modelo OSI) para troca automática de mensagens clínicas entre sistemas heterogéneos <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<p>O HL7 v2 implementa um grau de <strong>interoperabilidade semântica</strong>: os dados fluem automaticamente entre sistemas distintos com significado partilhado. A unidade de troca é a <em>mensagem</em>, enviada quando ocorre um evento clínico. O formato é texto estruturado, legível por humanos: segmentos separados por caracteres especiais (<em>pipes</em> e <em>carets</em>). A norma é aberta, mantida pelo consórcio HL7 International desde 1987 <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<p>O sucesso foi expressivo: estima-se que mais de 35 mil milhões de mensagens HL7 v2 sejam processadas por ano, em todo o mundo, e que o protocolo esteja presente em 95% dos hospitais <span class="citation" data-cites="Bhagat2019">(<a href="../referencias.html#ref-Bhagat2019" role="doc-biblioref">Bhagat, 2019</a>)</span>. A versão 3 (2005) e o FHIR (2011) coexistem com o v2 — não o substituíram.</p>
</section>
<section id="uma-norma-com-35-anos-de-longevidade" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="uma-norma-com-35-anos-de-longevidade"><span class="header-section-number">6.1.2</span> Uma norma com 35 anos de longevidade</h3>
<p>O HL7 v2 está profundamente embutido nos sistemas hospitalares existentes (HIS, LIS, RIS, PACS). Substituí-lo exigiria migrar décadas de interfaces activas. A <a href="#tbl-hl7-versoes" class="quarto-xref">Tabela&nbsp;<span>6.1</span></a> resume as versões principais.</p>
<div id="tbl-hl7-versoes" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-hl7-versoes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;6.1: Versões principais do HL7 v2 <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.
</figcaption>
<div aria-describedby="tbl-hl7-versoes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Ano</th>
<th>Versão</th>
<th>Marco</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1987</td>
<td>v2.0</td>
<td>Criação</td>
</tr>
<tr class="even">
<td>1990</td>
<td>v2.1</td>
<td>1.ª adopção generalizada</td>
</tr>
<tr class="odd">
<td>1994</td>
<td>v2.2</td>
<td>Refinamento</td>
</tr>
<tr class="even">
<td>1999</td>
<td>v2.3.1</td>
<td>Versão mais instalada</td>
</tr>
<tr class="odd">
<td>2003</td>
<td>v2.5</td>
<td>Expansão de domínios</td>
</tr>
<tr class="even">
<td>2014</td>
<td>v2.8</td>
<td>Última versão publicada</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>A longevidade não é acidente: o HL7 v2 alinha-se com o fluxo clínico real, é texto legível e tem um ecossistema maduro de ferramentas e consultores. Qualquer projecto de integração clínica hospitalar implica, directamente, lidar com mensagens HL7 v2 em produção <span class="citation" data-cites="BensonGrieve2021">(<a href="../referencias.html#ref-BensonGrieve2021" role="doc-biblioref">Benson &amp; Grieve, 2021</a>)</span>.</p>
</section>
<section id="o-modelo-trigger-event" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="o-modelo-trigger-event"><span class="header-section-number">6.1.3</span> O modelo trigger-event</h3>
<p>No HL7 v2, as mensagens não são enviadas de forma contínua — são criadas quando algo acontece no mundo real. Um <strong>trigger event</strong> é um acontecimento clínico que despoleta a criação de uma mensagem HL7. Sem evento não há mensagem: o sistema aguarda sempre que algo aconteça para comunicar. O conteúdo da mensagem depende do evento que a despoletou <span class="citation" data-cites="Bhagat2019">(<a href="../referencias.html#ref-Bhagat2019" role="doc-biblioref">Bhagat, 2019</a>)</span>.</p>
<!--
  Diagrama: modelo trigger-event.
  Linha temporal: evento clínico → geração da mensagem → envio → receptor.
  Paleta teal.
-->
<div style="overflow-x:auto; margin:1.5rem 0;">
<svg viewbox="0 0 680 200" xmlns="http://www.w3.org/2000/svg" style="width:100%;max-width:680px;font-family:sans-serif;">
  <rect width="680" height="200" rx="10" fill="#f8fbfc"></rect>

  <!-- Título -->
  <text x="340" y="22" text-anchor="middle" font-size="12" font-weight="bold" fill="#0a3d4a">Modelo Trigger-Event — HL7 v2</text>

  <!-- Bloco: Evento Clínico -->
  <rect x="20" y="40" width="140" height="80" rx="8" fill="#0a3d4a"></rect>
  <text x="90" y="72" text-anchor="middle" font-size="11" font-weight="bold" fill="#fff">Evento</text>
  <text x="90" y="88" text-anchor="middle" font-size="11" font-weight="bold" fill="#fff">Clínico</text>
  <text x="90" y="108" text-anchor="middle" font-size="9" fill="#e2f4f3">ex: internamento</text>

  <!-- Seta -->
  <line x1="162" y1="80" x2="218" y2="80" stroke="#0d7c8c" stroke-width="2" marker-end="url(#te1)"></line>
  <text x="190" y="72" text-anchor="middle" font-size="9" fill="#0d7c8c">despoleta</text>

  <!-- Bloco: Mensagem HL7 -->
  <rect x="220" y="40" width="140" height="80" rx="8" fill="#0d7c8c"></rect>
  <text x="290" y="72" text-anchor="middle" font-size="11" font-weight="bold" fill="#fff">Mensagem</text>
  <text x="290" y="88" text-anchor="middle" font-size="11" font-weight="bold" fill="#fff">HL7 v2</text>
  <text x="290" y="108" text-anchor="middle" font-size="9" fill="#e2f4f3">ADT^A01</text>

  <!-- Seta -->
  <line x1="362" y1="80" x2="418" y2="80" stroke="#1ab3a6" stroke-width="2" marker-end="url(#te2)"></line>
  <text x="390" y="72" text-anchor="middle" font-size="9" fill="#1ab3a6">enviada para</text>

  <!-- Bloco: Sistema Receptor -->
  <rect x="420" y="40" width="140" height="80" rx="8" fill="#1ab3a6"></rect>
  <text x="490" y="72" text-anchor="middle" font-size="11" font-weight="bold" fill="#fff">Sistema</text>
  <text x="490" y="88" text-anchor="middle" font-size="11" font-weight="bold" fill="#fff">Receptor</text>
  <text x="490" y="108" text-anchor="middle" font-size="9" fill="#0a3d4a">ex: PACS, LIS, EMR</text>

  <!-- Exemplos em baixo -->
  <rect x="20" y="140" width="140" height="22" rx="4" fill="#e2f4f3"></rect>
  <text x="90" y="155" text-anchor="middle" font-size="9" fill="#0a3d4a">Internamento → ADT^A01</text>
  <rect x="170" y="140" width="140" height="22" rx="4" fill="#e2f4f3"></rect>
  <text x="240" y="155" text-anchor="middle" font-size="9" fill="#0a3d4a">Pedido análise → ORM^O01</text>
  <rect x="320" y="140" width="140" height="22" rx="4" fill="#e2f4f3"></rect>
  <text x="390" y="155" text-anchor="middle" font-size="9" fill="#0a3d4a">Resultado → ORU^R01</text>
  <rect x="470" y="140" width="140" height="22" rx="4" fill="#e2f4f3"></rect>
  <text x="540" y="155" text-anchor="middle" font-size="9" fill="#0a3d4a">Alta → ADT^A03</text>

  <text x="340" y="188" text-anchor="middle" font-size="14" fill="#64748b">
    Figura 6.1 — Modelo trigger-event: evento clínico → mensagem HL7 → sistema receptor
  </text>

  <defs>
    <marker id="te1" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#0d7c8c"></path></marker>
    <marker id="te2" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#1ab3a6"></path></marker>
  </defs>
</svg>
</div>
</section>
<section id="tipos-de-mensagem-e-códigos-de-trigger" class="level3" data-number="6.1.4">
<h3 data-number="6.1.4" class="anchored" data-anchor-id="tipos-de-mensagem-e-códigos-de-trigger"><span class="header-section-number">6.1.4</span> Tipos de mensagem e códigos de trigger</h3>
<p>Cada mensagem HL7 é identificada por dois códigos unidos pelo caret (<code>^</code>): o tipo de mensagem e o trigger event. O tipo é uma sigla de três letras maiúsculas (ex: <code>ADT</code>); o trigger é uma letra seguida de dois dígitos (ex: <code>A01</code>). A <a href="#tbl-msg-types" class="quarto-xref">Tabela&nbsp;<span>6.2</span></a> apresenta os tipos mais relevantes em contexto hospitalar.</p>
<div id="tbl-msg-types" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-msg-types-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;6.2: Tipos de mensagem e triggers principais do HL7 v2 <span class="citation" data-cites="HL7_v28 Bhagat2019">(<a href="../referencias.html#ref-Bhagat2019" role="doc-biblioref">Bhagat, 2019</a>; <a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.
</figcaption>
<div aria-describedby="tbl-msg-types-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 32%">
<col style="width: 19%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>Tipo</th>
<th>Nome completo</th>
<th>Trigger</th>
<th>Evento clínico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ADT</td>
<td>Patient Administration</td>
<td>A01</td>
<td>Internamento</td>
</tr>
<tr class="even">
<td>ADT</td>
<td>Patient Administration</td>
<td>A02</td>
<td>Transferência</td>
</tr>
<tr class="odd">
<td>ADT</td>
<td>Patient Administration</td>
<td>A03</td>
<td>Alta</td>
</tr>
<tr class="even">
<td>ADT</td>
<td>Patient Administration</td>
<td>A04</td>
<td>Registo em ambulatório/urgência</td>
</tr>
<tr class="odd">
<td>ORM</td>
<td>Order Message</td>
<td>O01</td>
<td>Pedido de análise ou exame</td>
</tr>
<tr class="even">
<td>ORU</td>
<td>Observation Result</td>
<td>R01</td>
<td>Resultado de análise</td>
</tr>
<tr class="odd">
<td>MDM</td>
<td>Medical Document Management</td>
<td>T02</td>
<td>Criação de documento clínico</td>
</tr>
<tr class="even">
<td>DFT</td>
<td>Detail Financial Transaction</td>
<td>P03</td>
<td>Transacção financeira/faturação</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><code>ADT^A01</code> significa: <em>Patient Administration</em> (tipo) + <em>Admit</em> (trigger). Os dois códigos juntos identificam a mensagem de forma unívoca em qualquer implementação conforme.</p>
</section>
</section>
<section id="sec-hl7v2-estrutura" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="sec-hl7v2-estrutura"><span class="header-section-number">6.2</span> Estrutura de uma Mensagem HL7 v2</h2>
<section id="hierarquia-de-cinco-níveis" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="hierarquia-de-cinco-níveis"><span class="header-section-number">6.2.1</span> Hierarquia de cinco níveis</h3>
<p>Uma mensagem HL7 v2 é composta por cinco níveis de granularidade — do mais abrangente ao mais específico <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>:</p>
<ol type="1">
<li><strong>Mensagem</strong> — a unidade completa de troca (ex: <code>ADT^A01</code>)</li>
<li><strong>Segmento</strong> — agrupamento lógico de campos relacionados (ex: <code>MSH</code>, <code>PID</code>, <code>PV1</code>)</li>
<li><strong>Campo</strong> — unidade de dados dentro do segmento (ex: <code>PID-5</code> = nome do doente)</li>
<li><strong>Componente</strong> — subdivisão de um campo, separada por <code>^</code> (ex: apelido <code>^</code> nome)</li>
<li><strong>Subcomponente</strong> — subdivisão de um componente, separada por <code>&amp;</code> (ex: código <code>&amp;</code> instituição)</li>
</ol>
<!--
  Diagrama: hierarquia de 5 níveis HL7 v2.
  Caixas aninhadas ou cadeia vertical com setas.
-->
<div style="overflow-x:auto; margin:1.5rem 0;">
<svg viewbox="0 0 660 320" xmlns="http://www.w3.org/2000/svg" style="width:100%;max-width:660px;font-family:sans-serif;">
  <rect width="660" height="320" rx="10" fill="#f8fbfc"></rect>

  <!-- Nível 1: Mensagem -->
  <rect x="20" y="20" width="620" height="48" rx="8" fill="#0a3d4a"></rect>
  <text x="140" y="49" font-size="12" font-weight="bold" fill="#fff">Mensagem</text>
  <text x="340" y="49" font-size="11" fill="#e2f4f3">ADT^A01 — mensagem de internamento</text>

  <!-- Seta -->
  <line x1="330" y1="68" x2="330" y2="88" stroke="#0d7c8c" stroke-width="2" marker-end="url(#h1)"></line>

  <!-- Nível 2: Segmento -->
  <rect x="50" y="90" width="560" height="48" rx="8" fill="#0d7c8c"></rect>
  <text x="150" y="119" font-size="12" font-weight="bold" fill="#fff">Segmento</text>
  <text x="330" y="119" font-size="11" fill="#e2f4f3">MSH · EVN · PID · NK1 · PV1</text>

  <!-- Seta -->
  <line x1="330" y1="138" x2="330" y2="158" stroke="#1ab3a6" stroke-width="2" marker-end="url(#h2)"></line>

  <!-- Nível 3: Campo -->
  <rect x="80" y="160" width="500" height="48" rx="8" fill="#1ab3a6"></rect>
  <text x="160" y="189" font-size="12" font-weight="bold" fill="#fff">Campo</text>
  <text x="330" y="189" font-size="11" fill="#0a3d4a">PID-5:  BAPTISTA^JOAO^A^JUNIOR</text>

  <!-- Seta -->
  <line x1="330" y1="208" x2="330" y2="228" stroke="#0d7c8c" stroke-width="2" marker-end="url(#h1)"></line>

  <!-- Nível 4: Componente -->
  <rect x="110" y="230" width="440" height="48" rx="8" fill="#e2f4f3" stroke="#0d7c8c" stroke-width="1.5"></rect>
  <text x="180" y="259" font-size="12" font-weight="bold" fill="#0a3d4a">Componente</text>
  <text x="330" y="259" font-size="11" fill="#0d7c8c">BAPTISTA · JOAO · A · JUNIOR  (separados por ^)</text>

  <!-- Seta -->
  <line x1="330" y1="278" x2="330" y2="293" stroke="#1ab3a6" stroke-width="1.5" marker-end="url(#h2)"></line>

  <!-- Nível 5: Subcomponente -->
  <rect x="140" y="295" width="380" height="14" rx="4" fill="#e2f4f3" stroke="#1ab3a6" stroke-width="1"></rect>
  <text x="330" y="306" text-anchor="middle" font-size="9" fill="#0a3d4a">Subcomponente — separados por &amp;  (ex: código &amp; instituição)</text>

  <defs>
    <marker id="h1" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#0d7c8c"></path></marker>
    <marker id="h2" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#1ab3a6"></path></marker>
  </defs>
</svg>
</div>
</section>
<section id="os-delimitadores" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="os-delimitadores"><span class="header-section-number">6.2.2</span> Os delimitadores</h3>
<p>Cinco caracteres especiais definem a gramática do HL7 v2. São declarados nos campos <code>MSH-1</code> e <code>MSH-2</code> de cada mensagem, o que significa que um parser pode, em teoria, verificar a sua existência antes de processar qualquer outro campo <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<div id="tbl-delimitadores" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-delimitadores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;6.3: Delimitadores do HL7 v2 — declarados em MSH-1 e MSH-2 <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.
</figcaption>
<div aria-describedby="tbl-delimitadores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 18%">
<col style="width: 24%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Carácter</th>
<th>Nome</th>
<th>Função</th>
<th>Exemplo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>&amp;#124;</code></td>
<td>Pipe</td>
<td>Separador de campos</td>
<td><code>PID&amp;#124;1&amp;#124;&amp;#124;PAT001&amp;#124;&amp;#124;SILVA^ANA</code></td>
</tr>
<tr class="even">
<td><code>^</code></td>
<td>Caret</td>
<td>Separador de componentes</td>
<td><code>SILVA^ANA^M</code> → apelido ^ nome ^ inicial</td>
</tr>
<tr class="odd">
<td><code>~</code></td>
<td>Tilde</td>
<td>Separador de repetições</td>
<td><code>PID-3: ID001~ID002</code> → dois IDs alternativos</td>
</tr>
<tr class="even">
<td><code>\</code></td>
<td>Backslash</td>
<td>Carácter de escape</td>
<td><code>\F\</code> representa um pipe literal no conteúdo</td>
</tr>
<tr class="odd">
<td><code>&amp;</code></td>
<td>Ampersand</td>
<td>Separador de subcomponentes</td>
<td><code>ID001&amp;UTAD</code> → ID ^ instituição emissora</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><code>MSH-1</code> contém sempre o pipe — é o próprio delimitador de campos. <code>MSH-2</code> contém os quatro restantes na ordem <code>^~\&amp;</code>. Estes dois campos são os primeiros de qualquer mensagem e permitem ao receptor determinar os delimitadores antes de começar a fazer <em>parsing</em>.</p>
</section>
<section id="segmentos-a-unidade-lógica" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="segmentos-a-unidade-lógica"><span class="header-section-number">6.2.3</span> Segmentos: a unidade lógica</h3>
<p>Um <strong>segmento</strong> é um agrupamento lógico de campos relacionados. Começa com um identificador de três letras maiúsculas seguido de pipe. A posição determina o significado do campo — <code>PID-5</code> é sempre o nome do doente, independentemente da implementação. A <a href="#tbl-segmentos" class="quarto-xref">Tabela&nbsp;<span>6.4</span></a> descreve os segmentos essenciais num contexto ADT.</p>
<div id="tbl-segmentos" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-segmentos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;6.4: Segmentos essenciais em mensagens ADT <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.
</figcaption>
<div aria-describedby="tbl-segmentos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 21%">
<col style="width: 35%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>ID</th>
<th>Nome</th>
<th>Presença</th>
<th>Função</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MSH</td>
<td>Message Header</td>
<td>Obrigatório, único</td>
<td>Remetente, destinatário, tipo de mensagem, versão</td>
</tr>
<tr class="even">
<td>EVN</td>
<td>Event Type</td>
<td>Obrigatório</td>
<td>Tipo de evento e timestamp do acontecimento</td>
</tr>
<tr class="odd">
<td>PID</td>
<td>Patient Identification</td>
<td>Obrigatório</td>
<td>Nome, ID, data de nascimento, género, morada</td>
</tr>
<tr class="even">
<td>PV1</td>
<td>Patient Visit</td>
<td>Obrig./Opcional</td>
<td>Enfermaria, cama, médico assistente, serviço</td>
</tr>
<tr class="odd">
<td>NK1</td>
<td>Next of Kin</td>
<td>Opcional, repetível</td>
<td>Familiares ou contactos de emergência</td>
</tr>
<tr class="even">
<td>NTE</td>
<td>Notes and Comments</td>
<td>Opcional, repetível</td>
<td>Notas de texto livre</td>
</tr>
<tr class="odd">
<td>ERR</td>
<td>Error</td>
<td>Opcional</td>
<td>Detalhe de erros em mensagens ACK negativas</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>A notação de presença usa convenção normalizada: sem parêntesis indica campo obrigatório; <code>[ ]</code> indica opcional; <code>{ }</code> indica repetível; <code>[{ }]</code> indica opcional e repetível.</p>
</section>
<section id="campos-posicionalidade-e-estados-de-preenchimento" class="level3" data-number="6.2.4">
<h3 data-number="6.2.4" class="anchored" data-anchor-id="campos-posicionalidade-e-estados-de-preenchimento"><span class="header-section-number">6.2.4</span> Campos: posicionalidade e estados de preenchimento</h3>
<p>Dentro de um segmento, os campos são <strong>posicionais</strong>: o número da posição define o significado. Um parser conta os pipes para saber em que campo se encontra. Campos finais em branco podem ser omitidos — o parser infere a sua ausência.</p>
<p>Um campo pode estar em três estados distintos com semânticas diferentes <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>:</p>
<ul>
<li><strong>Preenchido</strong> (<em>Populated</em>) — o sistema remetente envia um valor. Exemplo: <code>19610615</code></li>
<li><strong>Não preenchido</strong> (<em>Not Populated</em>) — o campo existe mas está vazio; o remetente não tem o valor. Exemplo: <code>||</code></li>
<li><strong>Nulo</strong> (<em>Null</em>) — instrução explícita para o receptor apagar o valor que tem. Exemplo: <code>|""|</code></li>
</ul>
<p>A distinção entre <em>Não preenchido</em> e <em>Nulo</em> é crítica: confundi-los pode causar corrupção silenciosa de dados no sistema receptor. <em>Não preenchido</em> significa «não tenho o valor»; <em>Nulo</em> significa «apaga o valor que tens».</p>
</section>
</section>
<section id="sec-hl7v2-segmentos" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="sec-hl7v2-segmentos"><span class="header-section-number">6.3</span> Segmentos Essenciais</h2>
<section id="msh-cabeçalho-da-mensagem" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="msh-cabeçalho-da-mensagem"><span class="header-section-number">6.3.1</span> MSH — Cabeçalho da mensagem</h3>
<p>O MSH é sempre o primeiro segmento e define o contexto completo da mensagem. A <a href="#tbl-msh" class="quarto-xref">Tabela&nbsp;<span>6.5</span></a> descreve os campos mais relevantes, usando o exemplo das aulas:</p>
<pre><code>MSH|^~\&amp;|ADT1|ULSTMAD|SCLINICO|ULSTMAD|200707181123||ADT^A01^ADT_A01|MSG00001|P|2.8</code></pre>
<div id="tbl-msh" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-msh-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;6.5: Campos principais do segmento MSH <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.
</figcaption>
<div aria-describedby="tbl-msh-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 18%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Valor</th>
<th>Nome</th>
<th>Significado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MSH-1</td>
<td><code>&amp;#124;</code></td>
<td>Field Separator</td>
<td>O próprio pipe — único campo cujo valor é o delimitador</td>
</tr>
<tr class="even">
<td>MSH-2</td>
<td><code>^~\&amp;</code></td>
<td>Encoding Characters</td>
<td>Os quatro delimitadores secundários</td>
</tr>
<tr class="odd">
<td>MSH-3</td>
<td><code>ADT1</code></td>
<td>Sending Application</td>
<td>Aplicação remetente</td>
</tr>
<tr class="even">
<td>MSH-4</td>
<td><code>ULSTMAD</code></td>
<td>Sending Facility</td>
<td>Instituição remetente</td>
</tr>
<tr class="odd">
<td>MSH-5</td>
<td><code>SCLINICO</code></td>
<td>Receiving Application</td>
<td>Aplicação destinatária</td>
</tr>
<tr class="even">
<td>MSH-6</td>
<td><code>ULSTMAD</code></td>
<td>Receiving Facility</td>
<td>Instituição destinatária</td>
</tr>
<tr class="odd">
<td>MSH-7</td>
<td><code>200707181123</code></td>
<td>Date/Time</td>
<td>Timestamp: YYYYMMDDHHII</td>
</tr>
<tr class="even">
<td>MSH-9</td>
<td><code>ADT^A01^ADT_A01</code></td>
<td>Message Type</td>
<td>Tipo ^ Trigger ^ estrutura</td>
</tr>
<tr class="odd">
<td>MSH-10</td>
<td><code>MSG00001</code></td>
<td>Message Control ID</td>
<td>ID único — receptor devolve-o no ACK</td>
</tr>
<tr class="even">
<td>MSH-11</td>
<td><code>P</code></td>
<td>Processing ID</td>
<td>P = produção · T = teste · D = debug</td>
</tr>
<tr class="odd">
<td>MSH-12</td>
<td><code>2.8</code></td>
<td>Version ID</td>
<td>Versão do HL7 utilizada</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><code>MSH-10</code> (<em>Message Control ID</em>) é o campo que o receptor devolve na mensagem ACK para confirmar qual mensagem foi recebida — é o mecanismo de correlação entre pedido e resposta.</p>
</section>
<section id="evn-tipo-de-evento" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="evn-tipo-de-evento"><span class="header-section-number">6.3.2</span> EVN — Tipo de evento</h3>
<p>O segmento EVN regista o tipo de evento e os timestamps relevantes. Aparece imediatamente após o MSH:</p>
<pre><code>EVN|A01|200707181123||</code></pre>
<p>Os campos mais relevantes são: <code>EVN-1</code> (código do trigger, ex: <code>A01</code>), <code>EVN-2</code> (momento em que o evento foi registado no sistema) e <code>EVN-5</code> (identificador do operador que registou o evento). <code>EVN-3</code> (data planeada) e <code>EVN-4</code> (razão do evento) são opcionais e frequentemente em branco.</p>
<p>Na mensagem de transferência (<code>ADT^A02</code>), a diferença entre <code>EVN-2</code> (timestamp de registo) e <code>EVN-6</code> (hora real do evento) documenta o intervalo entre o acontecimento clínico e o seu registo administrativo.</p>
</section>
<section id="pid-identificação-do-doente" class="level3" data-number="6.3.3">
<h3 data-number="6.3.3" class="anchored" data-anchor-id="pid-identificação-do-doente"><span class="header-section-number">6.3.3</span> PID — Identificação do doente</h3>
<p>O segmento PID identifica univocamente o doente. A dissecação do exemplo das aulas ilustra a posicionalidade dos campos <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>:</p>
<pre><code>PID|1||PATID1234^^^ULSTMAD^MR~123456789^^^PORTUGAL^SS||BAPTISTA^JOAO^A^JUNIOR
||19610615|M|||45^RUADOCARMO^^VILAREAL^VILAREAL^5000-678|||92212345
||S||PATID12345001^2^M10^ADT1^AN^A|</code></pre>
<div id="tbl-pid" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;6.6: Campos principais do segmento PID, exemplo João Baptista <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.
</figcaption>
<div aria-describedby="tbl-pid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Valor</th>
<th>Significado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PID-1</td>
<td><code>1</code></td>
<td>Set ID — número de ordem do segmento</td>
</tr>
<tr class="even">
<td>PID-3</td>
<td><code>PATID1234^^^ULSTMAD^MR~123456789^^^PORTUGAL^SS</code></td>
<td>Dois IDs: MR interno + número de Segurança Social</td>
</tr>
<tr class="odd">
<td>PID-5</td>
<td><code>BAPTISTA^JOAO^A^JUNIOR</code></td>
<td>Nome: apelido ^ nome ^ inicial ^ sufixo</td>
</tr>
<tr class="even">
<td>PID-7</td>
<td><code>19610615</code></td>
<td>Data de nascimento — 15 Jun 1961</td>
</tr>
<tr class="odd">
<td>PID-8</td>
<td><code>M</code></td>
<td>Género — M (Male)</td>
</tr>
<tr class="even">
<td>PID-11</td>
<td><code>45^RUADOCARMO^^VILAREAL^...^5000-678</code></td>
<td>Morada estruturada: rua ^ ^ cidade ^ … ^ CP</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>O campo <code>PID-3</code> ilustra a repetição com <code>~</code>: dois grupos separados por tilde correspondem a dois identificadores distintos do mesmo doente — o ID interno do hospital e o número de Segurança Social. Dentro de cada grupo, <code>^</code> separa os componentes do identificador: valor, check digit, código de verificação, autoridade, tipo e nome da autoridade.</p>
</section>
<section id="pv1-visita-do-doente" class="level3" data-number="6.3.4">
<h3 data-number="6.3.4" class="anchored" data-anchor-id="pv1-visita-do-doente"><span class="header-section-number">6.3.4</span> PV1 — Visita do doente</h3>
<p>O segmento PV1 descreve a visita em curso: localização física, médico assistente e serviço clínico. O campo <code>PV1-3</code> usa uma estrutura de três componentes que identifica a localização: <code>enfermaria^quarto^cama</code>.</p>
<pre><code>PV1|1|I|CIR-10^64^01||||124340^SILVA^ANTONIO|||SUR||||ADM</code></pre>
<p><code>PV1-2</code> indica o tipo de visita (<code>I</code> = internamento; <code>O</code> = ambulatório; <code>E</code> = urgência). <code>PV1-7</code> identifica o médico assistente no formato <code>código^apelido^nome</code>. <code>PV1-10</code> indica o serviço clínico (<code>SUR</code> = cirurgia, <code>ICU</code> = unidade de cuidados intensivos). Na mensagem de alta, <code>PV1-44</code> e <code>PV1-45</code> registam, respectivamente, a data de admissão e a data de alta, permitindo calcular a duração do internamento.</p>
</section>
</section>
<section id="sec-hl7v2-ack" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="sec-hl7v2-ack"><span class="header-section-number">6.4</span> Confirmação de Mensagens: o ACK</h2>
<p>Após receber uma mensagem, o sistema destinatário envia uma mensagem <strong>ACK</strong> para confirmar o recebimento ou rejeitar com detalhe de erro. O ACK inclui sempre um segmento <code>MSA</code> cujo campo <code>MSA-2</code> repete o <code>MSH-10</code> da mensagem original, assegurando a correlação entre pedido e resposta <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<p>Os códigos de resposta do campo <code>MSA-1</code> são:</p>
<ul>
<li><strong>AA</strong> (<em>Application Accept</em>) — mensagem processada com sucesso</li>
<li><strong>AE</strong> (<em>Application Error</em>) — processada mas com erro no conteúdo</li>
<li><strong>AR</strong> (<em>Application Reject</em>) — rejeitada; não foi possível processar</li>
</ul>
<!--
  Diagrama: troca de mensagem + ACK.
  Sistema A → mensagem → Sistema B → ACK → Sistema A.
-->
<div style="overflow-x:auto; margin:1.5rem 0;">
<svg viewbox="0 0 640 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;max-width:640px;font-family:sans-serif;">
  <rect width="640" height="240" rx="10" fill="#f8fbfc"></rect>

  <!-- Sistema A -->
  <rect x="20" y="20" width="120" height="200" rx="8" fill="#0a3d4a" opacity="0.08" stroke="#0a3d4a" stroke-width="1.5"></rect>
  <rect x="20" y="20" width="120" height="32" rx="8" fill="#0a3d4a"></rect>
  <text x="80" y="41" text-anchor="middle" font-size="11" font-weight="bold" fill="#fff">Sistema A</text>
  <text x="80" y="58" text-anchor="middle" font-size="9" fill="#0a3d4a">(Remetente)</text>

  <!-- Sistema B -->
  <rect x="500" y="20" width="120" height="200" rx="8" fill="#0d7c8c" opacity="0.08" stroke="#0d7c8c" stroke-width="1.5"></rect>
  <rect x="500" y="20" width="120" height="32" rx="8" fill="#0d7c8c"></rect>
  <text x="560" y="41" text-anchor="middle" font-size="11" font-weight="bold" fill="#fff">Sistema B</text>
  <text x="560" y="58" text-anchor="middle" font-size="9" fill="#0d7c8c">(Receptor)</text>

  <!-- Seta: mensagem A→B -->
  <line x1="142" y1="100" x2="498" y2="100" stroke="#0a3d4a" stroke-width="2" marker-end="url(#ack1)"></line>
  <text x="320" y="90" text-anchor="middle" font-size="11" font-weight="bold" fill="#0a3d4a">ADT^A01  (MSH-10: MSG00001)</text>

  <!-- Seta: ACK B→A -->
  <line x1="498" y1="140" x2="142" y2="140" stroke="#1ab3a6" stroke-width="2" stroke-dasharray="6" marker-end="url(#ack2)"></line>
  <text x="320" y="130" text-anchor="middle" font-size="11" font-weight="bold" fill="#1ab3a6">ACK  (MSA-1: AA · MSA-2: MSG00001)</text>

  <!-- Códigos AA/AE/AR -->
  <rect x="180" y="160" width="280" height="50" rx="6" fill="#e2f4f3" stroke="#0d7c8c" stroke-width="1"></rect>
  <text x="320" y="177" text-anchor="middle" font-size="10" font-weight="bold" fill="#0a3d4a">MSA-1:</text>
  <text x="230" y="195" text-anchor="middle" font-size="10" fill="#16a34a">AA = Aceite</text>
  <text x="320" y="195" text-anchor="middle" font-size="10" fill="#dc2626">AE = Erro</text>
  <text x="410" y="195" text-anchor="middle" font-size="10" fill="#dc2626">AR = Rejeição</text>

  <text x="320" y="225" text-anchor="middle" font-size="14" fill="#64748b">
    Figura 6.2 — Troca de mensagem e ACK: MSA-2 correlaciona pedido com resposta (HL7 v2.8, §2)
  </text>

  <defs>
    <marker id="ack1" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#0a3d4a"></path></marker>
    <marker id="ack2" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#1ab3a6"></path></marker>
  </defs>
</svg>
</div>
<p>Num ACK negativo (<code>AE</code>), o segmento <code>ERR</code> fornece o detalhe do erro: o campo <code>ERR-2</code> identifica o segmento e a posição do campo com erro (<code>PID^5</code> = campo 5 do PID, nome do doente); <code>ERR-3</code> contém o código de erro; <code>ERR-4</code> indica a severidade (<code>E</code> = error, <code>W</code> = warning). Este mecanismo permite ao remetente diagnosticar exactamente o que falhou.</p>
</section>
<section id="sec-hl7v2-adt" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="sec-hl7v2-adt"><span class="header-section-number">6.5</span> Mensagens ADT: o Percurso Administrativo do Doente</h2>
<p>As mensagens <strong>ADT</strong> (<em>Admission, Discharge, Transfer</em>) acompanham cada mudança de estado administrativo do doente. Sempre que o doente entra, muda de serviço ou tem alta, uma mensagem ADT é gerada e distribuída por todos os sistemas subscritos. São as mensagens mais frequentes em qualquer hospital <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<p>Para ilustrar os três eventos centrais, as aulas utilizam um caso clínico completo: João A. Baptista Júnior, internado na ULSTMAD a 18 de Julho de 2007 para cirurgia, transferido para UCI na madrugada do dia seguinte e com alta a 25 de Julho.</p>
<section id="adta01-internamento" class="level3" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="adta01-internamento"><span class="header-section-number">6.5.1</span> ADT^A01 — Internamento</h3>
<p>O evento <code>A01</code> sinaliza que um doente foi admitido e colocado numa cama. É o início do processo hospitalar: o HIS gera o <code>ADT^A01</code> e distribui-o para todos os sistemas subscritos <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<p>No cenário em estudo, a 18 de Julho de 2007 às 11:23, João Baptista é internado no serviço de cirurgia (SUR), Enfermaria CIR-10, Quarto 64, Cama 01, com o Dr.&nbsp;António Silva (#124340) como médico assistente. A mensagem completa é:</p>
<pre><code>MSH|^~\&amp;|ADT1|ULSTMAD|SCLINICO|ULSTMAD|200707181123||ADT^A01^ADT_A01|MSG00001|P|2.8
EVN|A01|200707181123||
PID|1||PATID1234^^^ULSTMAD^MR~123456789^^^PORTUGAL^SS||BAPTISTA^JOAO^A^JUNIOR
||19610615|M|||45^RUADOCARMO^^VILAREAL^VILAREAL^5000-678|||92212345
||S||PATID12345001^2^M10^ADT1^AN^A|
NK1|1|PEREIRA^NILZA^F|SPO^SPOUSE||||NK^NEXT OF KIN
PV1|1|I|CIR-10^64^01||||124340^SILVA^ANTONIO|||SUR||||ADM</code></pre>
<p>A mensagem tem cinco segmentos: MSH (envelope), EVN (timestamp do evento), PID (identificação do doente, três linhas), NK1 (cônjuge Nilza F. Pereira) e PV1 (localização e médico). <code>PV1-3</code> usa a estrutura <code>CIR-10^64^01</code> — enfermaria ^ quarto ^ cama.</p>
</section>
<section id="adta02-transferência" class="level3" data-number="6.5.2">
<h3 data-number="6.5.2" class="anchored" data-anchor-id="adta02-transferência"><span class="header-section-number">6.5.2</span> ADT^A02 — Transferência</h3>
<p>O evento <code>A02</code> é gerado quando um doente internado muda de localização dentro do hospital. O PID mantém-se inalterado; o PV1 é actualizado com a nova localização, o novo médico responsável e o novo serviço <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<p>Na madrugada de 19 de Julho, o estado de João Baptista agrava-se por complicação pós-operatória. É transferido para UCI às 02:30; o evento é registado às 02:45:</p>
<pre><code>MSH|^~\&amp;|ADT1|ULSTMAD|SCLINICO|ULSTMAD|200707190245||ADT^A02^ADT_A02|000002|P|2.8||||
EVN|A02|200707190245||01||200707190230
PID|1||PATID1234^^^ULSTMAD^MR~123456789^^^PORTUGAL^SS||BAPTISTA^JOAO^A^JUNIOR
||19610615|M|||45^RUADOCARMO^^VILAREAL^VILAREAL^5000-678|GL||(259)123-456
||S||PATID12345001^2^M10^ADT1^AN^A|
PV1||I|UCI^01^02^ULSTMAD|||CIR-10^64^01|124340^SILVA^ANTONIO|856321^FERREIRA^CARLOS||ICU
|||||||856321^FERREIRA^CARLOS|S|||||||||||||||||||ULSTMAD|||||200707181123|</code></pre>
<p><code>EVN-2</code> (<code>200707190245</code>) regista o momento em que o evento foi registado no sistema; <code>EVN-6</code> (<code>200707190230</code>) regista a hora real da transferência. A diferença de 15 minutos documenta o atraso administrativo. No PV1: <code>PV1-3</code> = nova localização (<code>UCI^01^02</code>), <code>PV1-6</code> = localização anterior (<code>CIR-10^64^01</code>), <code>PV1-8</code> = Dr.&nbsp;Ferreira (novo responsável), <code>PV1-10</code> = serviço ICU.</p>
</section>
<section id="adta03-alta" class="level3" data-number="6.5.3">
<h3 data-number="6.5.3" class="anchored" data-anchor-id="adta03-alta"><span class="header-section-number">6.5.3</span> ADT^A03 — Alta</h3>
<p>O evento <code>A03</code> regista o fim da estadia hospitalar. O campo <code>PV1-36</code> indica o destino após a alta; os campos <code>PV1-44</code> e <code>PV1-45</code> registam, respectivamente, a data de admissão e a data de alta <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<p>A 25 de Julho de 2007 às 10:00, João Baptista recebe alta para domicílio com cuidados de saúde domiciliários (HH):</p>
<pre><code>MSH|^~\&amp;|ADT1|ULSTMAD|SCLINICO|ULSTMAD|200707251000||ADT^A03^ADT_A03|000003|P|2.8||||
EVN|A03|200707251000||01||200707251000
PID|1||PATID1234^^^ULSTMAD^MR~123456789^^^PORTUGAL^SS||BAPTISTA^JOAO^A^JUNIOR
||19610615|M|||45^RUADOCARMO^^VILAREAL^VILAREAL^5000-678|GL||(259)123-456
||S||PATID12345001^2^M10^ADT1^AN^A|
PV1||I|CIR-10^64^01||||124340^SILVA^ANTONIO|||SUR|||||||124340^SILVA^ANTONIO|S|1400|A
||||||||||||||||||HH|||ULSTMAD|||||200707181123|200707251000</code></pre>
<p><code>PV1-44</code> (<code>200707181123</code>) − <code>PV1-45</code> (<code>200707251000</code>) = 7 dias de internamento, calculável automaticamente por qualquer sistema receptor. Os destinos possíveis em <code>PV1-36</code> incluem: <code>HH</code> (cuidados domiciliários), <code>SNF</code> (lar especializado), <code>HSP</code> (transferência para outro hospital) e <code>EXP</code> (óbito).</p>
<!--
  Diagrama: sequência ADT A01 → A02 → A03 ao longo do tempo.
  Linha do tempo horizontal com três eventos.
-->
<div style="overflow-x:auto; margin:1.5rem 0;">
<svg viewbox="0 0 680 160" xmlns="http://www.w3.org/2000/svg" style="width:100%;max-width:680px;font-family:sans-serif;">
  <rect width="680" height="160" rx="10" fill="#f8fbfc"></rect>

  <!-- Linha do tempo -->
  <line x1="60" y1="80" x2="620" y2="80" stroke="#cbd5e1" stroke-width="2"></line>

  <!-- Evento 1: A01 -->
  <circle cx="140" cy="80" r="18" fill="#0a3d4a"></circle>
  <text x="140" y="85" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">A01</text>
  <text x="140" y="120" text-anchor="middle" font-size="10" font-weight="bold" fill="#0a3d4a">Internamento</text>
  <text x="140" y="134" text-anchor="middle" font-size="9" fill="#64748b">18 Jul 11:23</text>
  <text x="140" y="148" text-anchor="middle" font-size="9" fill="#64748b">CIR-10 · Dr. Silva</text>

  <!-- Evento 2: A02 -->
  <circle cx="340" cy="80" r="18" fill="#0d7c8c"></circle>
  <text x="340" y="85" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">A02</text>
  <text x="340" y="120" text-anchor="middle" font-size="10" font-weight="bold" fill="#0d7c8c">Transferência</text>
  <text x="340" y="134" text-anchor="middle" font-size="9" fill="#64748b">19 Jul 02:30</text>
  <text x="340" y="148" text-anchor="middle" font-size="9" fill="#64748b">UCI · Dr. Ferreira</text>

  <!-- Evento 3: A03 -->
  <circle cx="560" cy="80" r="18" fill="#1ab3a6"></circle>
  <text x="560" y="85" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">A03</text>
  <text x="560" y="120" text-anchor="middle" font-size="10" font-weight="bold" fill="#1ab3a6">Alta</text>
  <text x="560" y="134" text-anchor="middle" font-size="9" fill="#64748b">25 Jul 10:00</text>
  <text x="560" y="148" text-anchor="middle" font-size="9" fill="#64748b">Destino: HH</text>

  <!-- Duração -->
  <line x1="140" y1="55" x2="560" y2="55" stroke="#1ab3a6" stroke-width="1.5" stroke-dasharray="4" marker-start="url(#d1)" marker-end="url(#d2)"></line>
  <text x="350" y="46" text-anchor="middle" font-size="10" fill="#1ab3a6">7 dias de internamento</text>

  <defs>
    <marker id="d1" markerwidth="6" markerheight="6" refx="1" refy="3" orient="auto">
      <path d="M6,0 L0,3 L6,6 Z" fill="#1ab3a6"></path></marker>
    <marker id="d2" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#1ab3a6"></path></marker>
  </defs>
</svg>
</div>
<p>Figura 6.3 — Sequência ADT do caso João Baptista: internamento (A01), transferência (A02) e alta (A03).</p>
</section>
</section>
<section id="sec-hl7v2-limitacoes" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="sec-hl7v2-limitacoes"><span class="header-section-number">6.6</span> Limitações do HL7 v2</h2>
<section id="fragilidade-estrutural-ausência-de-schema-formal" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="fragilidade-estrutural-ausência-de-schema-formal"><span class="header-section-number">6.6.1</span> Fragilidade estrutural: ausência de schema formal</h3>
<p>O HL7 v2 não tem schema formal. Qualquer string é aceite em qualquer campo — a norma não define validação automática de formato. O campo <code>PID-7</code> (data de nascimento) devia conter <code>YYYYMMDD</code>, mas o receptor tem de aceitar o que chegar. Os erros de formato passam silenciosamente até aparecerem num relatório clínico errado <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<pre><code>PID|1||PAT001||SILVA^ANA||19850312|F|...    ← YYYYMMDD — correcto
PID|1||PAT001||SILVA^ANA||1985-03-12|F|...  ← aceite, mas formato diferente
PID|1||PAT001||SILVA^ANA||12/03/1985|F|...  ← aceite, outro dialecto</code></pre>
<p>Uma base de dados com coluna <code>DATE</code> rejeita automaticamente <code>15/06/1961</code>. No HL7 v2, esse mecanismo não existe. Cada sistema que envia mensagens tem o seu próprio dialecto de datas, géneros e códigos; o integration engine acumula regras de normalização por sistema. Com o crescimento da rede hospitalar, este trabalho de normalização torna-se um custo permanente.</p>
</section>
<section id="semântica-fraca-tabelas-de-valores-locais" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="semântica-fraca-tabelas-de-valores-locais"><span class="header-section-number">6.6.2</span> Semântica fraca: tabelas de valores locais</h3>
<p>O HL7 v2 define campos pelo nome e posição, mas não define o vocabulário dos seus valores. A especificação prevê <strong>user-defined tables</strong>: cada hospital escolhe os seus próprios códigos. O resultado é que o que devia ser um vocabulário partilhado se torna um dialecto privado de cada instituição <span class="citation" data-cites="BensonGrieve2021">(<a href="../referencias.html#ref-BensonGrieve2021" role="doc-biblioref">Benson &amp; Grieve, 2021</a>)</span>.</p>
<p>O exemplo mais comum é <code>PV1-4</code> (tipo de admissão):</p>
<div id="tbl-semantica" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-semantica-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;6.7: Semântica fraca: o mesmo campo, valores incompatíveis entre hospitais <span class="citation" data-cites="BensonGrieve2021">(<a href="../referencias.html#ref-BensonGrieve2021" role="doc-biblioref">Benson &amp; Grieve, 2021</a>)</span>.
</figcaption>
<div aria-describedby="tbl-semantica-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Hospital</th>
<th>Valor em PV1-4</th>
<th>Significado local</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hospital A</td>
<td><code>U</code></td>
<td>Urgência</td>
</tr>
<tr class="even">
<td>Hospital B</td>
<td><code>E</code></td>
<td><em>Emergency</em></td>
</tr>
<tr class="odd">
<td>Hospital C</td>
<td><code>1</code></td>
<td>Urgente</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Os três hospitais estão conformes com a especificação — e são incompatíveis entre si. O mesmo problema existe em <code>PID-8</code> (género), serviço clínico, tipo de diagnóstico e estado civil: cada campo com <em>user-defined table</em> é um potencial ponto de incompatibilidade. Dois sistemas «HL7 v2 conformes» podem ter semânticas completamente distintas e precisar de mapeamento bilateral antes de qualquer troca de dados.</p>
</section>
<section id="z-segments-extensões-privadas" class="level3" data-number="6.6.3">
<h3 data-number="6.6.3" class="anchored" data-anchor-id="z-segments-extensões-privadas"><span class="header-section-number">6.6.3</span> Z-segments: extensões privadas</h3>
<p>Qualquer segmento cujo identificador começa por <code>Z</code> é reservado para uso local. A especificação proíbe Z-segments na norma normalizada — são propositadamente privados e opacos. Cada hospital cria os seus próprios campos extra (ex: <code>ZPI</code> para informação de seguro, <code>ZIN</code> para dados de subsistema de saúde) sem os publicar <span class="citation" data-cites="HL7_v28">(<a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<p>O problema torna-se evidente quando se tenta integrar dois hospitais:</p>
<pre><code>Hospital A:  ZIN|ADSE|GROUP001|PLANO_B
Hospital B:  ZSG|ADSE|PLANO_B|GROUP001</code></pre>
<p>O mesmo conteúdo, identificadores diferentes, ordem dos campos diferente — incompatíveis entre si. Um parser externo não sabe o que significam <code>ZIN</code> ou <code>ZSG</code>; tem de ser configurado caso a caso, por acordo bilateral. Os Z-segments são o exemplo mais visível de um problema mais amplo: a norma é suficientemente aberta para gerar incompatibilidades mesmo entre implementações conformes.</p>
</section>
<section id="parsing-complexidade-oculta" class="level3" data-number="6.6.4">
<h3 data-number="6.6.4" class="anchored" data-anchor-id="parsing-complexidade-oculta"><span class="header-section-number">6.6.4</span> Parsing: complexidade oculta</h3>
<p>Processar uma mensagem HL7 v2 é mais trabalhoso do que simplesmente separar strings por pipe. Identificam-se três fontes principais de complexidade <span class="citation" data-cites="Bhagat2019">(<a href="../referencias.html#ref-Bhagat2019" role="doc-biblioref">Bhagat, 2019</a>)</span>:</p>
<ul>
<li><strong>Campos repetíveis com <code>~</code></strong> — um campo pode ter múltiplos valores separados por tilde; <code>PID-3</code> pode conter vários identificadores do mesmo doente; o parser tem de gerir listas, não valores únicos.</li>
<li><strong>Z-segments opacos</strong> — um parser genérico não sabe o que significam <code>ZIN</code>, <code>ZPI</code> ou <code>ZCU</code>; tem de ser configurado caso a caso.</li>
<li><strong>Diferenças entre versões</strong> — o mesmo campo pode ter estruturas distintas entre v2.3 e v2.8; num ambiente real, diferentes sistemas enviam diferentes versões e o parser tem de lidar com todas.</li>
</ul>
<p>Não existe parser universal para HL7 v2: cada ambiente exige regras específicas por sistema e por versão.</p>
</section>
<section id="o-integration-engine-a-peça-obrigatória" class="level3" data-number="6.6.5">
<h3 data-number="6.6.5" class="anchored" data-anchor-id="o-integration-engine-a-peça-obrigatória"><span class="header-section-number">6.6.5</span> O integration engine: a peça obrigatória</h3>
<p>As limitações anteriores convergem num ponto: qualquer ambiente HL7 v2 real precisa de um <strong>middleware de integração</strong> — tipicamente designado <em>integration engine</em>. Produtos como Mirth Connect, Rhapsody ou InterSystems Ensemble recebem mensagens de múltiplos sistemas, normalizam formatos, mapeiam tabelas locais, traduzem Z-segments e encaminham para os destinatários correctos <span class="citation" data-cites="BensonGrieve2021">(<a href="../referencias.html#ref-BensonGrieve2021" role="doc-biblioref">Benson &amp; Grieve, 2021</a>)</span>.</p>
<!--
  Diagrama: integration engine — N sistemas emissores → engine → N sistemas receptores.
-->
<div style="overflow-x:auto; margin:1.5rem 0;">
<svg viewbox="0 0 680 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;max-width:680px;font-family:sans-serif;">
  <rect width="680" height="240" rx="10" fill="#f8fbfc"></rect>

  <!-- Sistemas emissores (esq) -->
  <rect x="15" y="30" width="110" height="32" rx="6" fill="#0a3d4a"></rect>
  <text x="70" y="51" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">HIS (Admissões)</text>
  <rect x="15" y="80" width="110" height="32" rx="6" fill="#0a3d4a"></rect>
  <text x="70" y="101" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">LIS (Laboratório)</text>
  <rect x="15" y="130" width="110" height="32" rx="6" fill="#0a3d4a"></rect>
  <text x="70" y="151" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">RIS (Radiologia)</text>

  <!-- Setas → engine -->
  <line x1="127" y1="46" x2="245" y2="100" stroke="#0d7c8c" stroke-width="1.5" marker-end="url(#ie1)"></line>
  <line x1="127" y1="96" x2="245" y2="110" stroke="#0d7c8c" stroke-width="1.5" marker-end="url(#ie1)"></line>
  <line x1="127" y1="146" x2="245" y2="120" stroke="#0d7c8c" stroke-width="1.5" marker-end="url(#ie1)"></line>

  <!-- Integration Engine -->
  <rect x="247" y="70" width="186" height="80" rx="10" fill="#0d7c8c"></rect>
  <text x="340" y="98" text-anchor="middle" font-size="12" font-weight="bold" fill="#fff">Integration Engine</text>
  <text x="340" y="115" text-anchor="middle" font-size="9" fill="#e2f4f3">Mirth · Rhapsody · Ensemble</text>
  <text x="340" y="130" text-anchor="middle" font-size="9" fill="#e2f4f3">Normaliza · Mapeia · Encaminha</text>

  <!-- Setas engine → receptores -->
  <line x1="435" y1="100" x2="548" y2="50" stroke="#1ab3a6" stroke-width="1.5" marker-end="url(#ie2)"></line>
  <line x1="435" y1="110" x2="548" y2="100" stroke="#1ab3a6" stroke-width="1.5" marker-end="url(#ie2)"></line>
  <line x1="435" y1="120" x2="548" y2="150" stroke="#1ab3a6" stroke-width="1.5" marker-end="url(#ie2)"></line>

  <!-- Sistemas receptores (dir) -->
  <rect x="550" y="30" width="110" height="32" rx="6" fill="#1ab3a6"></rect>
  <text x="605" y="51" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">EMR (Clínico)</text>
  <rect x="550" y="82" width="110" height="32" rx="6" fill="#1ab3a6"></rect>
  <text x="605" y="103" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">Farmácia</text>
  <rect x="550" y="134" width="110" height="32" rx="6" fill="#1ab3a6"></rect>
  <text x="605" y="155" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">PACS (Imagem)</text>

  <text x="340" y="225" text-anchor="middle" font-size="14" fill="#64748b">
    Figura 6.4 — Integration engine: peça obrigatória em qualquer ambiente HL7 v2 real
  </text>

  <defs>
    <marker id="ie1" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#0d7c8c"></path></marker>
    <marker id="ie2" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#1ab3a6"></path></marker>
  </defs>
</svg>
</div>
<p>O integration engine não é opcional: é a peça que torna o HL7 v2 funcionar em ambientes heterogéneos. O custo que a norma não mostra é o custo de manutenção deste middleware: cada novo sistema que entra na rede exige análise, mapeamento e testes. Com N sistemas a crescer, o número de interfaces — e o custo de as manter — cresce com ele. É este o limite estrutural do modelo bilateral que o HL7 v2 impõe.</p>
</section>
<section id="balanço-o-que-o-hl7-v2-resolveu-e-onde-ficou-aquém" class="level3" data-number="6.6.6">
<h3 data-number="6.6.6" class="anchored" data-anchor-id="balanço-o-que-o-hl7-v2-resolveu-e-onde-ficou-aquém"><span class="header-section-number">6.6.6</span> Balanço: o que o HL7 v2 resolveu e onde ficou aquém</h3>
<p>O HL7 v2 resolveu um problema real: eliminou a troca manual de dados entre sistemas hospitalares, criou um modelo trigger-event alinhado com o fluxo clínico, e sobreviveu 35 anos de evolução tecnológica. Os seus limites só se tornaram evidentes quando a escala cresceu.</p>
<div id="tbl-balanco" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-balanco-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;6.8: Balanço do HL7 v2 <span class="citation" data-cites="HL7_v28 BensonGrieve2021">(<a href="../referencias.html#ref-BensonGrieve2021" role="doc-biblioref">Benson &amp; Grieve, 2021</a>; <a href="../referencias.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.
</figcaption>
<div aria-describedby="tbl-balanco-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 45%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th>Aspecto</th>
<th>Avaliação</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Eliminação da troca manual de dados</td>
<td>Resolvido</td>
</tr>
<tr class="even">
<td>Modelo trigger-event alinhado com o fluxo clínico</td>
<td>Resolvido</td>
</tr>
<tr class="odd">
<td>Adopção global (95% dos hospitais)</td>
<td>Resolvido</td>
</tr>
<tr class="even">
<td>Ecossistema maduro de ferramentas</td>
<td>Resolvido</td>
</tr>
<tr class="odd">
<td>Schema formal com validação automática</td>
<td>Não resolvido</td>
</tr>
<tr class="even">
<td>Semântica partilhada entre instituições</td>
<td>Não resolvido</td>
</tr>
<tr class="odd">
<td>Extensões privadas interoperáveis (Z-segments)</td>
<td>Não resolvido</td>
</tr>
<tr class="even">
<td>Parser universal</td>
<td>Não resolvido</td>
</tr>
<tr class="odd">
<td>Custo de integração proporcional ao número de sistemas</td>
<td>Não resolvido</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="sec-hl7v2-sintese" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="sec-hl7v2-sintese"><span class="header-section-number">6.7</span> Síntese e Exercícios</h2>
<section id="exercícios-de-consolidação" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercícios-de-consolidação">Exercícios de consolidação</h3>
<ol type="1">
<li><p>Um sistema de laboratório (LIS) recebe um pedido de análise enviado pelo sistema de prescrição. Identifique: (a) o tipo de mensagem HL7 utilizado; (b) o trigger event; (c) os campos do MSH que permitem ao LIS saber quem enviou o pedido e a que versão do HL7 obedece.</p></li>
<li><p>O campo <code>PID-3</code> de uma mensagem contém o valor <code>PATID1234^^^ULSTMAD^MR~123456789^^^PORTUGAL^SS</code>. Explique o significado do carácter <code>~</code> neste contexto e identifique os dois identificadores presentes, indicando o tipo de cada um.</p></li>
<li><p>Num ACK negativo (AE), o segmento ERR contém <code>ERR||PID^5|101^Required field missing|E</code>. Interprete cada componente deste segmento e explique a consequência prática para o sistema remetente.</p></li>
<li><p>Dois hospitais utilizam <code>PV1-4</code> com valores diferentes para classificar as admissões de urgência: Hospital X usa <code>U</code>, Hospital Y usa <code>E</code>. Ambos afirmam ser conformes com a especificação HL7 v2. Explique como é possível esta situação e que componente de arquitectura é necessário para os integrar.</p></li>
<li><p>Um hospital pretende transmitir dados de seguros de saúde (subsistema ADSE, número de grupo, plano) entre o HIS e a farmácia. A especificação HL7 v2 não define nenhum segmento standard para este efeito. Que mecanismo prevê a norma? Quais as implicações para a interoperabilidade com outros hospitais?</p></li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-BensonGrieve2021" class="csl-entry" role="listitem">
Benson, T., &amp; Grieve, G. (2021). <em>Principles of Health Interoperability: <span>FHIR</span>, <span>HL7</span> and <span>SNOMED CT</span></em> (4.ª ed.). Springer. <a href="https://doi.org/10.1007/978-3-030-56883-2">https://doi.org/10.1007/978-3-030-56883-2</a>
</div>
<div id="ref-Bhagat2019" class="csl-entry" role="listitem">
Bhagat, R. (2019). <em><span>HL7</span> for Busy Professionals</em>. Anchiove.
</div>
<div id="ref-HL7_v28" class="csl-entry" role="listitem">
HL7 International. (2014). <em><span>HL7</span> Messaging Standard Version 2.8</em>. <a href="https://www.hl7.org/implement/standards/product_brief.cfm?product_id=185" class="uri">https://www.hl7.org/implement/standards/product_brief.cfm?product_id=185</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script>
document.addEventListener('DOMContentLoaded', function () {
  var path = window.location.pathname;
  var isEn = path.indexOf('/en/') !== -1;

  var target, label, title;
  if (isEn) {
    target = path.replace('/en/', '/');
    label  = '🇵🇹 PT';
    title  = 'Mudar para Português';
  } else {
    var m = path.match(/^(\/[^/]*)(\/.*)$/);
    target = m ? m[1] + '/en' + m[2] : '/en/';
    label  = '🇬🇧 EN';
    title  = 'Switch to English';
  }

  var btn = document.createElement('a');
  btn.href  = target;
  btn.title = title;
  btn.textContent = label;
  btn.style.cssText =
    'position:fixed;top:68px;right:16px;z-index:9999;' +
    'background:#0d7c8c;color:#fff;border-radius:6px;' +
    'padding:5px 11px;font-size:13px;font-weight:600;' +
    'text-decoration:none;box-shadow:0 2px 8px rgba(0,0,0,.2);' +
    'transition:background .2s;';
  btn.onmouseover = function () { this.style.background = '#0a3d4a'; };
  btn.onmouseout  = function () { this.style.background = '#0d7c8c'; };
  document.body.appendChild(btn);
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../capitulos/cap05.html" class="pagination-link" aria-label="Serviços DICOM e Arquitectura PACS">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Serviços DICOM e Arquitectura PACS</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../referencias.html" class="pagination-link" aria-label="Referências">
        <span class="nav-page-text">Referências</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Informática Médica — Mestrado em Engenharia Biomédica · UTAD</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>