<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-GB" xml:lang="en-GB"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; HL7 v2 — Message Model and Limitations – Medical Informatics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../references.html" rel="next">
<link href="../capitulos/cap05.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de84f8d6bb715db06a919283c2d1e787.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-9a023c9ade86a60361e96e3e3f11bc54.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-61bc4ac84974e0785b3107ee93e74bfb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-bc9f1d3aef906c45e091843ae87821a0.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../assets/css/custom.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../capitulos/cap06.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">HL7 v2 — Message Model and Limitations</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Medical Informatics</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Foundations of Medical Informatics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Hospital Information Systems and Electronic Health Records</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Terminologies and Semantic Interoperability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">DICOM as a Data Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">DICOM Services and PACS Architecture</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap06.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">HL7 v2 — Message Model and Limitations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-hl7v2-model" id="toc-sec-hl7v2-model" class="nav-link active" data-scroll-target="#sec-hl7v2-model"><span class="header-section-number">6.1</span> HL7 v2 and the Message Model</a>
  <ul class="collapse">
  <li><a href="#the-problem-hl7-v2-solved" id="toc-the-problem-hl7-v2-solved" class="nav-link" data-scroll-target="#the-problem-hl7-v2-solved"><span class="header-section-number">6.1.1</span> The problem HL7 v2 solved</a></li>
  <li><a href="#a-standard-with-35-years-of-longevity" id="toc-a-standard-with-35-years-of-longevity" class="nav-link" data-scroll-target="#a-standard-with-35-years-of-longevity"><span class="header-section-number">6.1.2</span> A standard with 35 years of longevity</a></li>
  <li><a href="#the-trigger-event-model" id="toc-the-trigger-event-model" class="nav-link" data-scroll-target="#the-trigger-event-model"><span class="header-section-number">6.1.3</span> The trigger-event model</a></li>
  <li><a href="#message-types-and-trigger-codes" id="toc-message-types-and-trigger-codes" class="nav-link" data-scroll-target="#message-types-and-trigger-codes"><span class="header-section-number">6.1.4</span> Message types and trigger codes</a></li>
  </ul></li>
  <li><a href="#sec-hl7v2-structure" id="toc-sec-hl7v2-structure" class="nav-link" data-scroll-target="#sec-hl7v2-structure"><span class="header-section-number">6.2</span> Structure of an HL7 v2 Message</a>
  <ul class="collapse">
  <li><a href="#five-level-hierarchy" id="toc-five-level-hierarchy" class="nav-link" data-scroll-target="#five-level-hierarchy"><span class="header-section-number">6.2.1</span> Five-level hierarchy</a></li>
  <li><a href="#the-delimiters" id="toc-the-delimiters" class="nav-link" data-scroll-target="#the-delimiters"><span class="header-section-number">6.2.2</span> The delimiters</a></li>
  <li><a href="#segments-the-logical-unit" id="toc-segments-the-logical-unit" class="nav-link" data-scroll-target="#segments-the-logical-unit"><span class="header-section-number">6.2.3</span> Segments: the logical unit</a></li>
  <li><a href="#fields-positional-and-fill-states" id="toc-fields-positional-and-fill-states" class="nav-link" data-scroll-target="#fields-positional-and-fill-states"><span class="header-section-number">6.2.4</span> Fields: positional and fill states</a></li>
  </ul></li>
  <li><a href="#sec-hl7v2-segments" id="toc-sec-hl7v2-segments" class="nav-link" data-scroll-target="#sec-hl7v2-segments"><span class="header-section-number">6.3</span> Essential Segments</a>
  <ul class="collapse">
  <li><a href="#msh-message-header" id="toc-msh-message-header" class="nav-link" data-scroll-target="#msh-message-header"><span class="header-section-number">6.3.1</span> MSH — Message header</a></li>
  <li><a href="#evn-event-type" id="toc-evn-event-type" class="nav-link" data-scroll-target="#evn-event-type"><span class="header-section-number">6.3.2</span> EVN — Event type</a></li>
  <li><a href="#pid-patient-identification" id="toc-pid-patient-identification" class="nav-link" data-scroll-target="#pid-patient-identification"><span class="header-section-number">6.3.3</span> PID — Patient identification</a></li>
  <li><a href="#pv1-patient-visit" id="toc-pv1-patient-visit" class="nav-link" data-scroll-target="#pv1-patient-visit"><span class="header-section-number">6.3.4</span> PV1 — Patient visit</a></li>
  </ul></li>
  <li><a href="#sec-hl7v2-ack" id="toc-sec-hl7v2-ack" class="nav-link" data-scroll-target="#sec-hl7v2-ack"><span class="header-section-number">6.4</span> Message Confirmation: the ACK</a></li>
  <li><a href="#sec-hl7v2-adt" id="toc-sec-hl7v2-adt" class="nav-link" data-scroll-target="#sec-hl7v2-adt"><span class="header-section-number">6.5</span> ADT Messages: the Patient’s Administrative Journey</a>
  <ul class="collapse">
  <li><a href="#adta01-admission" id="toc-adta01-admission" class="nav-link" data-scroll-target="#adta01-admission"><span class="header-section-number">6.5.1</span> ADT^A01 — Admission</a></li>
  <li><a href="#adta02-transfer" id="toc-adta02-transfer" class="nav-link" data-scroll-target="#adta02-transfer"><span class="header-section-number">6.5.2</span> ADT^A02 — Transfer</a></li>
  <li><a href="#adta03-discharge" id="toc-adta03-discharge" class="nav-link" data-scroll-target="#adta03-discharge"><span class="header-section-number">6.5.3</span> ADT^A03 — Discharge</a></li>
  </ul></li>
  <li><a href="#sec-hl7v2-limitations" id="toc-sec-hl7v2-limitations" class="nav-link" data-scroll-target="#sec-hl7v2-limitations"><span class="header-section-number">6.6</span> HL7 v2 Limitations</a>
  <ul class="collapse">
  <li><a href="#structural-fragility-no-formal-schema" id="toc-structural-fragility-no-formal-schema" class="nav-link" data-scroll-target="#structural-fragility-no-formal-schema"><span class="header-section-number">6.6.1</span> Structural fragility: no formal schema</a></li>
  <li><a href="#weak-semantics-local-value-tables" id="toc-weak-semantics-local-value-tables" class="nav-link" data-scroll-target="#weak-semantics-local-value-tables"><span class="header-section-number">6.6.2</span> Weak semantics: local value tables</a></li>
  <li><a href="#z-segments-private-extensions" id="toc-z-segments-private-extensions" class="nav-link" data-scroll-target="#z-segments-private-extensions"><span class="header-section-number">6.6.3</span> Z-segments: private extensions</a></li>
  <li><a href="#parsing-hidden-complexity" id="toc-parsing-hidden-complexity" class="nav-link" data-scroll-target="#parsing-hidden-complexity"><span class="header-section-number">6.6.4</span> Parsing: hidden complexity</a></li>
  <li><a href="#the-integration-engine-the-required-piece" id="toc-the-integration-engine-the-required-piece" class="nav-link" data-scroll-target="#the-integration-engine-the-required-piece"><span class="header-section-number">6.6.5</span> The integration engine: the required piece</a></li>
  <li><a href="#balance-what-hl7-v2-solved-and-where-it-fell-short" id="toc-balance-what-hl7-v2-solved-and-where-it-fell-short" class="nav-link" data-scroll-target="#balance-what-hl7-v2-solved-and-where-it-fell-short"><span class="header-section-number">6.6.6</span> Balance: what HL7 v2 solved and where it fell short</a></li>
  </ul></li>
  <li><a href="#sec-hl7v2-summary" id="toc-sec-hl7v2-summary" class="nav-link" data-scroll-target="#sec-hl7v2-summary"><span class="header-section-number">6.7</span> Summary and Exercises</a>
  <ul class="collapse">
  <li><a href="#consolidation-exercises" id="toc-consolidation-exercises" class="nav-link" data-scroll-target="#consolidation-exercises">Consolidation exercises</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">HL7 v2 — Message Model and Limitations</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-hl7v2-model" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="sec-hl7v2-model"><span class="header-section-number">6.1</span> HL7 v2 and the Message Model</h2>
<section id="the-problem-hl7-v2-solved" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="the-problem-hl7-v2-solved"><span class="header-section-number">6.1.1</span> The problem HL7 v2 solved</h3>
<p>Before HL7, each hospital information system operated as an isolated silo. Exchanging clinical data between systems — for example, between the admissions system and the laboratory — required manual intervention or proprietary point-to-point solutions. <strong>HL7 v2</strong> was designed to solve this problem: an application-layer protocol (OSI layer 7) for the automatic exchange of clinical messages between heterogeneous systems <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<p>HL7 v2 achieves a degree of <strong>semantic interoperability</strong>: data flows automatically between different systems with shared meaning. The unit of exchange is a <em>message</em>, sent when a clinical event occurs. The format is structured text, human-readable: segments separated by special characters (<em>pipes</em> and <em>carets</em>). The standard is open, maintained by the HL7 International consortium since 1987 <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<p>The adoption was remarkable: more than 35 billion HL7 v2 messages are estimated to be processed every year worldwide, and the protocol is present in 95% of hospitals <span class="citation" data-cites="Bhagat2019">(<a href="../references.html#ref-Bhagat2019" role="doc-biblioref">Bhagat, 2019</a>)</span>. Version 3 (2005) and FHIR (2011) coexist with v2 — they have not replaced it.</p>
</section>
<section id="a-standard-with-35-years-of-longevity" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="a-standard-with-35-years-of-longevity"><span class="header-section-number">6.1.2</span> A standard with 35 years of longevity</h3>
<p>HL7 v2 is deeply embedded in existing hospital systems (HIS, LIS, RIS, PACS). Replacing it would require migrating decades of active interfaces. <a href="#tbl-hl7-versions" class="quarto-xref">Table&nbsp;<span>6.1</span></a> summarises the main versions.</p>
<div id="tbl-hl7-versions" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-hl7-versions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: Main versions of HL7 v2 <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.
</figcaption>
<div aria-describedby="tbl-hl7-versions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Year</th>
<th>Version</th>
<th>Milestone</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1987</td>
<td>v2.0</td>
<td>Creation</td>
</tr>
<tr class="even">
<td>1990</td>
<td>v2.1</td>
<td>First widespread adoption</td>
</tr>
<tr class="odd">
<td>1994</td>
<td>v2.2</td>
<td>Refinement</td>
</tr>
<tr class="even">
<td>1999</td>
<td>v2.3.1</td>
<td>Most widely installed</td>
</tr>
<tr class="odd">
<td>2003</td>
<td>v2.5</td>
<td>Domain expansion</td>
</tr>
<tr class="even">
<td>2014</td>
<td>v2.8</td>
<td>Last published version</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The longevity is not accidental: HL7 v2 aligns with real clinical workflows, is human-readable text, and benefits from a mature ecosystem of tools and consultants. Any clinical integration project in a hospital setting directly involves HL7 v2 messages in production <span class="citation" data-cites="BensonGrieve2021">(<a href="../references.html#ref-BensonGrieve2021" role="doc-biblioref">Benson &amp; Grieve, 2021</a>)</span>.</p>
</section>
<section id="the-trigger-event-model" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="the-trigger-event-model"><span class="header-section-number">6.1.3</span> The trigger-event model</h3>
<p>In HL7 v2, messages are not sent continuously — they are created when something happens in the real world. A <strong>trigger event</strong> is a clinical occurrence that causes an HL7 message to be generated. Without an event there is no message: the system always waits for something to happen before communicating. The content of the message depends on the event that triggered it <span class="citation" data-cites="Bhagat2019">(<a href="../references.html#ref-Bhagat2019" role="doc-biblioref">Bhagat, 2019</a>)</span>.</p>
<!--
  Diagram: trigger-event model.
  Timeline: clinical event → message generation → send → receiver.
  Teal palette.
-->
<div style="overflow-x:auto; margin:1.5rem 0;">
<svg viewbox="0 0 680 200" xmlns="http://www.w3.org/2000/svg" style="width:100%;max-width:680px;font-family:sans-serif;">
  <rect width="680" height="200" rx="10" fill="#f8fbfc"></rect>

  <!-- Title -->
  <text x="340" y="22" text-anchor="middle" font-size="12" font-weight="bold" fill="#0a3d4a">Trigger-Event Model — HL7 v2</text>

  <!-- Block: Clinical Event -->
  <rect x="20" y="40" width="140" height="80" rx="8" fill="#0a3d4a"></rect>
  <text x="90" y="72" text-anchor="middle" font-size="11" font-weight="bold" fill="#fff">Clinical</text>
  <text x="90" y="88" text-anchor="middle" font-size="11" font-weight="bold" fill="#fff">Event</text>
  <text x="90" y="108" text-anchor="middle" font-size="9" fill="#e2f4f3">e.g. admission</text>

  <!-- Arrow -->
  <line x1="162" y1="80" x2="218" y2="80" stroke="#0d7c8c" stroke-width="2" marker-end="url(#te1)"></line>
  <text x="190" y="72" text-anchor="middle" font-size="9" fill="#0d7c8c">triggers</text>

  <!-- Block: HL7 Message -->
  <rect x="220" y="40" width="140" height="80" rx="8" fill="#0d7c8c"></rect>
  <text x="290" y="72" text-anchor="middle" font-size="11" font-weight="bold" fill="#fff">HL7 v2</text>
  <text x="290" y="88" text-anchor="middle" font-size="11" font-weight="bold" fill="#fff">Message</text>
  <text x="290" y="108" text-anchor="middle" font-size="9" fill="#e2f4f3">ADT^A01</text>

  <!-- Arrow -->
  <line x1="362" y1="80" x2="418" y2="80" stroke="#1ab3a6" stroke-width="2" marker-end="url(#te2)"></line>
  <text x="390" y="72" text-anchor="middle" font-size="9" fill="#1ab3a6">sent to</text>

  <!-- Block: Receiving System -->
  <rect x="420" y="40" width="140" height="80" rx="8" fill="#1ab3a6"></rect>
  <text x="490" y="72" text-anchor="middle" font-size="11" font-weight="bold" fill="#fff">Receiving</text>
  <text x="490" y="88" text-anchor="middle" font-size="11" font-weight="bold" fill="#fff">System</text>
  <text x="490" y="108" text-anchor="middle" font-size="9" fill="#0a3d4a">e.g. PACS, LIS, EMR</text>

  <!-- Examples -->
  <rect x="20" y="140" width="140" height="22" rx="4" fill="#e2f4f3"></rect>
  <text x="90" y="155" text-anchor="middle" font-size="9" fill="#0a3d4a">Admission → ADT^A01</text>
  <rect x="170" y="140" width="140" height="22" rx="4" fill="#e2f4f3"></rect>
  <text x="240" y="155" text-anchor="middle" font-size="9" fill="#0a3d4a">Order request → ORM^O01</text>
  <rect x="320" y="140" width="140" height="22" rx="4" fill="#e2f4f3"></rect>
  <text x="390" y="155" text-anchor="middle" font-size="9" fill="#0a3d4a">Lab result → ORU^R01</text>
  <rect x="470" y="140" width="140" height="22" rx="4" fill="#e2f4f3"></rect>
  <text x="540" y="155" text-anchor="middle" font-size="9" fill="#0a3d4a">Discharge → ADT^A03</text>

  <text x="340" y="188" text-anchor="middle" font-size="14" fill="#64748b">
    Figure 6.1 — Trigger-event model: clinical event → HL7 message → receiving system
  </text>

  <defs>
    <marker id="te1" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#0d7c8c"></path></marker>
    <marker id="te2" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#1ab3a6"></path></marker>
  </defs>
</svg>
</div>
</section>
<section id="message-types-and-trigger-codes" class="level3" data-number="6.1.4">
<h3 data-number="6.1.4" class="anchored" data-anchor-id="message-types-and-trigger-codes"><span class="header-section-number">6.1.4</span> Message types and trigger codes</h3>
<p>Each HL7 message is identified by two codes joined by a caret (<code>^</code>): the message type and the trigger event. The type is a three-letter uppercase acronym (e.g.&nbsp;<code>ADT</code>); the trigger is a letter followed by two digits (e.g.&nbsp;<code>A01</code>). <a href="#tbl-msg-types" class="quarto-xref">Table&nbsp;<span>6.2</span></a> lists the most relevant types in a hospital context.</p>
<div id="tbl-msg-types" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-msg-types-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.2: Message types and main triggers in HL7 v2 <span class="citation" data-cites="HL7_v28 Bhagat2019">(<a href="../references.html#ref-Bhagat2019" role="doc-biblioref">Bhagat, 2019</a>; <a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.
</figcaption>
<div aria-describedby="tbl-msg-types-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 26%">
<col style="width: 21%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Type</th>
<th>Full name</th>
<th>Trigger</th>
<th>Clinical event</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ADT</td>
<td>Patient Administration</td>
<td>A01</td>
<td>Patient admission</td>
</tr>
<tr class="even">
<td>ADT</td>
<td>Patient Administration</td>
<td>A02</td>
<td>Patient transfer</td>
</tr>
<tr class="odd">
<td>ADT</td>
<td>Patient Administration</td>
<td>A03</td>
<td>Patient discharge</td>
</tr>
<tr class="even">
<td>ADT</td>
<td>Patient Administration</td>
<td>A04</td>
<td>Outpatient / emergency registration</td>
</tr>
<tr class="odd">
<td>ORM</td>
<td>Order Message</td>
<td>O01</td>
<td>Lab or exam order</td>
</tr>
<tr class="even">
<td>ORU</td>
<td>Observation Result</td>
<td>R01</td>
<td>Lab result</td>
</tr>
<tr class="odd">
<td>MDM</td>
<td>Medical Document Management</td>
<td>T02</td>
<td>Clinical document creation</td>
</tr>
<tr class="even">
<td>DFT</td>
<td>Detail Financial Transaction</td>
<td>P03</td>
<td>Financial / billing transaction</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><code>ADT^A01</code> means: <em>Patient Administration</em> (type) + <em>Admit</em> (trigger). The two codes together uniquely identify the message in any conformant implementation.</p>
</section>
</section>
<section id="sec-hl7v2-structure" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="sec-hl7v2-structure"><span class="header-section-number">6.2</span> Structure of an HL7 v2 Message</h2>
<section id="five-level-hierarchy" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="five-level-hierarchy"><span class="header-section-number">6.2.1</span> Five-level hierarchy</h3>
<p>An HL7 v2 message is composed of five levels of granularity — from the broadest to the most specific <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>:</p>
<ol type="1">
<li><strong>Message</strong> — the complete unit of exchange (e.g.&nbsp;<code>ADT^A01</code>)</li>
<li><strong>Segment</strong> — a logical grouping of related fields (e.g.&nbsp;<code>MSH</code>, <code>PID</code>, <code>PV1</code>)</li>
<li><strong>Field</strong> — a data unit within a segment (e.g.&nbsp;<code>PID-5</code> = patient name)</li>
<li><strong>Component</strong> — a subdivision of a field, separated by <code>^</code> (e.g.&nbsp;family name <code>^</code> given name)</li>
<li><strong>Subcomponent</strong> — a subdivision of a component, separated by <code>&amp;</code> (e.g.&nbsp;code <code>&amp;</code> institution)</li>
</ol>
<!--
  Diagram: HL7 v2 five-level hierarchy.
-->
<div style="overflow-x:auto; margin:1.5rem 0;">
<svg viewbox="0 0 660 320" xmlns="http://www.w3.org/2000/svg" style="width:100%;max-width:660px;font-family:sans-serif;">
  <rect width="660" height="320" rx="10" fill="#f8fbfc"></rect>

  <!-- Level 1: Message -->
  <rect x="20" y="20" width="620" height="48" rx="8" fill="#0a3d4a"></rect>
  <text x="140" y="49" font-size="12" font-weight="bold" fill="#fff">Message</text>
  <text x="340" y="49" font-size="11" fill="#e2f4f3">ADT^A01 — admission message</text>

  <line x1="330" y1="68" x2="330" y2="88" stroke="#0d7c8c" stroke-width="2" marker-end="url(#h1)"></line>

  <!-- Level 2: Segment -->
  <rect x="50" y="90" width="560" height="48" rx="8" fill="#0d7c8c"></rect>
  <text x="150" y="119" font-size="12" font-weight="bold" fill="#fff">Segment</text>
  <text x="330" y="119" font-size="11" fill="#e2f4f3">MSH · EVN · PID · NK1 · PV1</text>

  <line x1="330" y1="138" x2="330" y2="158" stroke="#1ab3a6" stroke-width="2" marker-end="url(#h2)"></line>

  <!-- Level 3: Field -->
  <rect x="80" y="160" width="500" height="48" rx="8" fill="#1ab3a6"></rect>
  <text x="160" y="189" font-size="12" font-weight="bold" fill="#fff">Field</text>
  <text x="330" y="189" font-size="11" fill="#0a3d4a">PID-5:  BAPTISTA^JOAO^A^JUNIOR</text>

  <line x1="330" y1="208" x2="330" y2="228" stroke="#0d7c8c" stroke-width="2" marker-end="url(#h1)"></line>

  <!-- Level 4: Component -->
  <rect x="110" y="230" width="440" height="48" rx="8" fill="#e2f4f3" stroke="#0d7c8c" stroke-width="1.5"></rect>
  <text x="180" y="259" font-size="12" font-weight="bold" fill="#0a3d4a">Component</text>
  <text x="330" y="259" font-size="11" fill="#0d7c8c">BAPTISTA · JOAO · A · JUNIOR  (separated by ^)</text>

  <line x1="330" y1="278" x2="330" y2="293" stroke="#1ab3a6" stroke-width="1.5" marker-end="url(#h2)"></line>

  <!-- Level 5: Subcomponent -->
  <rect x="140" y="295" width="380" height="14" rx="4" fill="#e2f4f3" stroke="#1ab3a6" stroke-width="1"></rect>
  <text x="330" y="306" text-anchor="middle" font-size="9" fill="#0a3d4a">Subcomponent — separated by &amp;  (e.g. code &amp; issuing institution)</text>

  <defs>
    <marker id="h1" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#0d7c8c"></path></marker>
    <marker id="h2" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#1ab3a6"></path></marker>
  </defs>
</svg>
</div>
</section>
<section id="the-delimiters" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="the-delimiters"><span class="header-section-number">6.2.2</span> The delimiters</h3>
<p>Five special characters define the grammar of HL7 v2. They are declared in fields <code>MSH-1</code> and <code>MSH-2</code> of every message, meaning a parser can verify their presence before processing any other field <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<div id="tbl-delimiters" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-delimiters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.3: HL7 v2 delimiters — declared in MSH-1 and MSH-2 <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.
</figcaption>
<div aria-describedby="tbl-delimiters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 16%">
<col style="width: 27%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Character</th>
<th>Name</th>
<th>Function</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>&amp;#124;</code></td>
<td>Pipe</td>
<td>Field separator</td>
<td><code>PID&amp;#124;1&amp;#124;&amp;#124;PAT001&amp;#124;&amp;#124;SILVA^ANA</code></td>
</tr>
<tr class="even">
<td><code>^</code></td>
<td>Caret</td>
<td>Component separator</td>
<td><code>SILVA^ANA^M</code> → family name ^ given name ^ initial</td>
</tr>
<tr class="odd">
<td><code>~</code></td>
<td>Tilde</td>
<td>Repetition separator</td>
<td><code>PID-3: ID001~ID002</code> → two alternative IDs</td>
</tr>
<tr class="even">
<td><code>\</code></td>
<td>Backslash</td>
<td>Escape character</td>
<td><code>\F\</code> represents a literal pipe in content</td>
</tr>
<tr class="odd">
<td><code>&amp;</code></td>
<td>Ampersand</td>
<td>Subcomponent separator</td>
<td><code>ID001&amp;UTAD</code> → ID ^ issuing institution</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><code>MSH-1</code> always contains the pipe — it is the field separator itself. <code>MSH-2</code> contains the other four in order <code>^~\&amp;</code>. These two fields are the first in any message and allow the receiver to determine the delimiters before beginning to parse.</p>
</section>
<section id="segments-the-logical-unit" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="segments-the-logical-unit"><span class="header-section-number">6.2.3</span> Segments: the logical unit</h3>
<p>A <strong>segment</strong> is a logical grouping of related fields. It begins with a three-letter uppercase identifier followed by a pipe. The position determines the meaning of the field — <code>PID-5</code> is always the patient name, regardless of the implementation. <a href="#tbl-segments" class="quarto-xref">Table&nbsp;<span>6.4</span></a> describes the essential segments in an ADT context.</p>
<div id="tbl-segments" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-segments-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.4: Essential segments in ADT messages <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.
</figcaption>
<div aria-describedby="tbl-segments-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 20%">
<col style="width: 34%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>ID</th>
<th>Name</th>
<th>Presence</th>
<th>Function</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MSH</td>
<td>Message Header</td>
<td>Mandatory, unique</td>
<td>Sender, receiver, message type, version</td>
</tr>
<tr class="even">
<td>EVN</td>
<td>Event Type</td>
<td>Mandatory</td>
<td>Event type and occurrence timestamp</td>
</tr>
<tr class="odd">
<td>PID</td>
<td>Patient Identification</td>
<td>Mandatory</td>
<td>Name, ID, date of birth, gender, address</td>
</tr>
<tr class="even">
<td>PV1</td>
<td>Patient Visit</td>
<td>Mand./Optional</td>
<td>Ward, bed, attending physician, service</td>
</tr>
<tr class="odd">
<td>NK1</td>
<td>Next of Kin</td>
<td>Optional, repeatable</td>
<td>Family members or emergency contacts</td>
</tr>
<tr class="even">
<td>NTE</td>
<td>Notes and Comments</td>
<td>Optional, repeatable</td>
<td>Free-text notes</td>
</tr>
<tr class="odd">
<td>ERR</td>
<td>Error</td>
<td>Optional</td>
<td>Error detail in negative ACK messages</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The presence notation follows a normalised convention: no brackets means mandatory; <code>[ ]</code> means optional; <code>{ }</code> means repeatable; <code>[{ }]</code> means optional and repeatable.</p>
</section>
<section id="fields-positional-and-fill-states" class="level3" data-number="6.2.4">
<h3 data-number="6.2.4" class="anchored" data-anchor-id="fields-positional-and-fill-states"><span class="header-section-number">6.2.4</span> Fields: positional and fill states</h3>
<p>Within a segment, fields are <strong>positional</strong>: the position number defines the meaning. A parser counts the pipes to know which field it is in. Trailing empty fields may be omitted — the parser infers their absence.</p>
<p>A field can be in three distinct states with different semantics <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>:</p>
<ul>
<li><strong>Populated</strong> — the sending system provides a value. Example: <code>19610615</code></li>
<li><strong>Not Populated</strong> — the field exists but is empty; the sender does not have the value. Example: <code>||</code></li>
<li><strong>Null</strong> — an explicit instruction for the receiver to delete the value it holds. Example: <code>|""|</code></li>
</ul>
<p>The distinction between <em>Not Populated</em> and <em>Null</em> is critical: confusing the two can cause silent data corruption in the receiving system. <em>Not Populated</em> means “I don’t have the value”; <em>Null</em> means “delete the value you have”.</p>
</section>
</section>
<section id="sec-hl7v2-segments" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="sec-hl7v2-segments"><span class="header-section-number">6.3</span> Essential Segments</h2>
<section id="msh-message-header" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="msh-message-header"><span class="header-section-number">6.3.1</span> MSH — Message header</h3>
<p>The MSH is always the first segment and defines the full context of the message. <a href="#tbl-msh" class="quarto-xref">Table&nbsp;<span>6.5</span></a> describes the most relevant fields, using the example from the lectures:</p>
<pre><code>MSH|^~\&amp;|ADT1|ULSTMAD|SCLINICO|ULSTMAD|200707181123||ADT^A01^ADT_A01|MSG00001|P|2.8</code></pre>
<div id="tbl-msh" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-msh-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.5: Main fields of the MSH segment <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.
</figcaption>
<div aria-describedby="tbl-msh-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 20%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Value</th>
<th>Name</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MSH-1</td>
<td><code>&amp;#124;</code></td>
<td>Field Separator</td>
<td>The pipe itself — the only field whose value is the delimiter</td>
</tr>
<tr class="even">
<td>MSH-2</td>
<td><code>^~\&amp;</code></td>
<td>Encoding Characters</td>
<td>The four secondary delimiters</td>
</tr>
<tr class="odd">
<td>MSH-3</td>
<td><code>ADT1</code></td>
<td>Sending Application</td>
<td>Sending application</td>
</tr>
<tr class="even">
<td>MSH-4</td>
<td><code>ULSTMAD</code></td>
<td>Sending Facility</td>
<td>Sending institution</td>
</tr>
<tr class="odd">
<td>MSH-5</td>
<td><code>SCLINICO</code></td>
<td>Receiving Application</td>
<td>Receiving application</td>
</tr>
<tr class="even">
<td>MSH-6</td>
<td><code>ULSTMAD</code></td>
<td>Receiving Facility</td>
<td>Receiving institution</td>
</tr>
<tr class="odd">
<td>MSH-7</td>
<td><code>200707181123</code></td>
<td>Date/Time</td>
<td>Timestamp: YYYYMMDDHHII</td>
</tr>
<tr class="even">
<td>MSH-9</td>
<td><code>ADT^A01^ADT_A01</code></td>
<td>Message Type</td>
<td>Type ^ Trigger ^ structure</td>
</tr>
<tr class="odd">
<td>MSH-10</td>
<td><code>MSG00001</code></td>
<td>Message Control ID</td>
<td>Unique ID — returned by receiver in ACK</td>
</tr>
<tr class="even">
<td>MSH-11</td>
<td><code>P</code></td>
<td>Processing ID</td>
<td>P = production · T = test · D = debug</td>
</tr>
<tr class="odd">
<td>MSH-12</td>
<td><code>2.8</code></td>
<td>Version ID</td>
<td>HL7 version used</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><code>MSH-10</code> (<em>Message Control ID</em>) is the field the receiver returns in the ACK message to confirm which message was received — it is the correlation mechanism between request and response.</p>
</section>
<section id="evn-event-type" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="evn-event-type"><span class="header-section-number">6.3.2</span> EVN — Event type</h3>
<p>The EVN segment records the event type and the relevant timestamps. It appears immediately after the MSH:</p>
<pre><code>EVN|A01|200707181123||</code></pre>
<p>The most relevant fields are: <code>EVN-1</code> (trigger code, e.g.&nbsp;<code>A01</code>), <code>EVN-2</code> (moment the event was recorded in the system) and <code>EVN-5</code> (identifier of the operator who recorded the event). <code>EVN-3</code> (planned date) and <code>EVN-4</code> (event reason) are optional and frequently empty.</p>
<p>In a transfer message (<code>ADT^A02</code>), the difference between <code>EVN-2</code> (recording timestamp) and <code>EVN-6</code> (actual event time) documents the interval between the clinical occurrence and its administrative registration.</p>
</section>
<section id="pid-patient-identification" class="level3" data-number="6.3.3">
<h3 data-number="6.3.3" class="anchored" data-anchor-id="pid-patient-identification"><span class="header-section-number">6.3.3</span> PID — Patient identification</h3>
<p>The PID segment uniquely identifies the patient. Dissecting the example from the lectures illustrates field positional semantics <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>:</p>
<pre><code>PID|1||PATID1234^^^ULSTMAD^MR~123456789^^^PORTUGAL^SS||BAPTISTA^JOAO^A^JUNIOR
||19610615|M|||45^RUADOCARMO^^VILAREAL^VILAREAL^5000-678|||92212345
||S||PATID12345001^2^M10^ADT1^AN^A|</code></pre>
<div id="tbl-pid" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.6: Main fields of the PID segment, João Baptista example <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.
</figcaption>
<div aria-describedby="tbl-pid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 30%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Value</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PID-1</td>
<td><code>1</code></td>
<td>Set ID — segment order number</td>
</tr>
<tr class="even">
<td>PID-3</td>
<td><code>PATID1234^^^ULSTMAD^MR~123456789^^^PORTUGAL^SS</code></td>
<td>Two IDs: internal MR + Social Security number</td>
</tr>
<tr class="odd">
<td>PID-5</td>
<td><code>BAPTISTA^JOAO^A^JUNIOR</code></td>
<td>Name: family name ^ given name ^ initial ^ suffix</td>
</tr>
<tr class="even">
<td>PID-7</td>
<td><code>19610615</code></td>
<td>Date of birth — 15 Jun 1961</td>
</tr>
<tr class="odd">
<td>PID-8</td>
<td><code>M</code></td>
<td>Gender — M (Male)</td>
</tr>
<tr class="even">
<td>PID-11</td>
<td><code>45^RUADOCARMO^^VILAREAL^...^5000-678</code></td>
<td>Structured address: street ^ ^ city ^ … ^ postal code</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Field <code>PID-3</code> illustrates repetition with <code>~</code>: two groups separated by tilde correspond to two distinct identifiers for the same patient — the hospital’s internal ID and the Social Security number. Within each group, <code>^</code> separates the identifier components: value, check digit, verification code, assigning authority, type and authority name.</p>
</section>
<section id="pv1-patient-visit" class="level3" data-number="6.3.4">
<h3 data-number="6.3.4" class="anchored" data-anchor-id="pv1-patient-visit"><span class="header-section-number">6.3.4</span> PV1 — Patient visit</h3>
<p>The PV1 segment describes the current visit: physical location, attending physician and clinical service. Field <code>PV1-3</code> uses a three-component structure identifying the location: <code>ward^room^bed</code>.</p>
<pre><code>PV1|1|I|CIR-10^64^01||||124340^SILVA^ANTONIO|||SUR||||ADM</code></pre>
<p><code>PV1-2</code> indicates the visit type (<code>I</code> = inpatient; <code>O</code> = outpatient; <code>E</code> = emergency). <code>PV1-7</code> identifies the attending physician as <code>code^family name^given name</code>. <code>PV1-10</code> indicates the clinical service (<code>SUR</code> = surgery, <code>ICU</code> = intensive care unit). In a discharge message, <code>PV1-44</code> and <code>PV1-45</code> record the admission date and discharge date respectively, allowing any receiving system to calculate the length of stay.</p>
</section>
</section>
<section id="sec-hl7v2-ack" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="sec-hl7v2-ack"><span class="header-section-number">6.4</span> Message Confirmation: the ACK</h2>
<p>After receiving a message, the destination system sends an <strong>ACK</strong> message to confirm receipt or to reject with error detail. The ACK always includes an <code>MSA</code> segment whose field <code>MSA-2</code> repeats the <code>MSH-10</code> of the original message, ensuring correlation between request and response <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<p>The response codes in field <code>MSA-1</code> are:</p>
<ul>
<li><strong>AA</strong> (<em>Application Accept</em>) — message processed successfully</li>
<li><strong>AE</strong> (<em>Application Error</em>) — processed but with a content error</li>
<li><strong>AR</strong> (<em>Application Reject</em>) — rejected; processing was not possible</li>
</ul>
<!--
  Diagram: message exchange + ACK.
-->
<div style="overflow-x:auto; margin:1.5rem 0;">
<svg viewbox="0 0 640 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;max-width:640px;font-family:sans-serif;">
  <rect width="640" height="240" rx="10" fill="#f8fbfc"></rect>

  <!-- System A -->
  <rect x="20" y="20" width="120" height="200" rx="8" fill="#0a3d4a" opacity="0.08" stroke="#0a3d4a" stroke-width="1.5"></rect>
  <rect x="20" y="20" width="120" height="32" rx="8" fill="#0a3d4a"></rect>
  <text x="80" y="41" text-anchor="middle" font-size="11" font-weight="bold" fill="#fff">System A</text>
  <text x="80" y="58" text-anchor="middle" font-size="9" fill="#0a3d4a">(Sender)</text>

  <!-- System B -->
  <rect x="500" y="20" width="120" height="200" rx="8" fill="#0d7c8c" opacity="0.08" stroke="#0d7c8c" stroke-width="1.5"></rect>
  <rect x="500" y="20" width="120" height="32" rx="8" fill="#0d7c8c"></rect>
  <text x="560" y="41" text-anchor="middle" font-size="11" font-weight="bold" fill="#fff">System B</text>
  <text x="560" y="58" text-anchor="middle" font-size="9" fill="#0d7c8c">(Receiver)</text>

  <!-- Arrow: message A→B -->
  <line x1="142" y1="100" x2="498" y2="100" stroke="#0a3d4a" stroke-width="2" marker-end="url(#ack1)"></line>
  <text x="320" y="90" text-anchor="middle" font-size="11" font-weight="bold" fill="#0a3d4a">ADT^A01  (MSH-10: MSG00001)</text>

  <!-- Arrow: ACK B→A -->
  <line x1="498" y1="140" x2="142" y2="140" stroke="#1ab3a6" stroke-width="2" stroke-dasharray="6" marker-end="url(#ack2)"></line>
  <text x="320" y="130" text-anchor="middle" font-size="11" font-weight="bold" fill="#1ab3a6">ACK  (MSA-1: AA · MSA-2: MSG00001)</text>

  <!-- Response codes -->
  <rect x="180" y="160" width="280" height="50" rx="6" fill="#e2f4f3" stroke="#0d7c8c" stroke-width="1"></rect>
  <text x="320" y="177" text-anchor="middle" font-size="10" font-weight="bold" fill="#0a3d4a">MSA-1:</text>
  <text x="230" y="195" text-anchor="middle" font-size="10" fill="#16a34a">AA = Accepted</text>
  <text x="320" y="195" text-anchor="middle" font-size="10" fill="#dc2626">AE = Error</text>
  <text x="410" y="195" text-anchor="middle" font-size="10" fill="#dc2626">AR = Rejected</text>

  <text x="320" y="225" text-anchor="middle" font-size="14" fill="#64748b">
    Figure 6.2 — Message exchange and ACK: MSA-2 correlates request with response (HL7 v2.8, §2)
  </text>

  <defs>
    <marker id="ack1" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#0a3d4a"></path></marker>
    <marker id="ack2" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#1ab3a6"></path></marker>
  </defs>
</svg>
</div>
<p>In a negative ACK (<code>AE</code>), the <code>ERR</code> segment provides error detail: field <code>ERR-2</code> identifies the segment and field position with the error (<code>PID^5</code> = field 5 of PID, patient name); <code>ERR-3</code> contains the error code; <code>ERR-4</code> indicates severity (<code>E</code> = error, <code>W</code> = warning). This mechanism allows the sender to diagnose exactly what failed.</p>
</section>
<section id="sec-hl7v2-adt" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="sec-hl7v2-adt"><span class="header-section-number">6.5</span> ADT Messages: the Patient’s Administrative Journey</h2>
<p><strong>ADT</strong> (<em>Admission, Discharge, Transfer</em>) messages track each administrative state change of the patient. Whenever a patient is admitted, changes service, or is discharged, an ADT message is generated and distributed to all subscribed systems. They are the most frequent messages in any hospital <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<p>To illustrate the three central events, the lectures use a complete clinical case: João A. Baptista Júnior, admitted to ULSTMAD on 18 July 2007 for surgery, transferred to ICU early the following morning, and discharged on 25 July.</p>
<section id="adta01-admission" class="level3" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="adta01-admission"><span class="header-section-number">6.5.1</span> ADT^A01 — Admission</h3>
<p>The <code>A01</code> event signals that a patient has been admitted and assigned a bed. It is the start of the hospital process: the HIS generates the <code>ADT^A01</code> and distributes it to all subscribed systems <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<p>In the case study, on 18 July 2007 at 11:23, João Baptista is admitted to the surgery service (SUR), Ward CIR-10, Room 64, Bed 01, with Dr.&nbsp;António Silva (#124340) as attending physician. The complete message is:</p>
<pre><code>MSH|^~\&amp;|ADT1|ULSTMAD|SCLINICO|ULSTMAD|200707181123||ADT^A01^ADT_A01|MSG00001|P|2.8
EVN|A01|200707181123||
PID|1||PATID1234^^^ULSTMAD^MR~123456789^^^PORTUGAL^SS||BAPTISTA^JOAO^A^JUNIOR
||19610615|M|||45^RUADOCARMO^^VILAREAL^VILAREAL^5000-678|||92212345
||S||PATID12345001^2^M10^ADT1^AN^A|
NK1|1|PEREIRA^NILZA^F|SPO^SPOUSE||||NK^NEXT OF KIN
PV1|1|I|CIR-10^64^01||||124340^SILVA^ANTONIO|||SUR||||ADM</code></pre>
<p>The message has five segments: MSH (envelope), EVN (event timestamp), PID (patient identification, three lines), NK1 (spouse Nilza F. Pereira) and PV1 (location and physician). <code>PV1-3</code> uses the structure <code>CIR-10^64^01</code> — ward ^ room ^ bed.</p>
</section>
<section id="adta02-transfer" class="level3" data-number="6.5.2">
<h3 data-number="6.5.2" class="anchored" data-anchor-id="adta02-transfer"><span class="header-section-number">6.5.2</span> ADT^A02 — Transfer</h3>
<p>The <code>A02</code> event is generated when an admitted patient changes location within the hospital. The PID remains unchanged; the PV1 is updated with the new location, new responsible physician and new service <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<p>In the early hours of 19 July, João Baptista’s condition worsens due to a post-operative complication. He is transferred to the ICU at 02:30; the event is recorded at 02:45:</p>
<pre><code>MSH|^~\&amp;|ADT1|ULSTMAD|SCLINICO|ULSTMAD|200707190245||ADT^A02^ADT_A02|000002|P|2.8||||
EVN|A02|200707190245||01||200707190230
PID|1||PATID1234^^^ULSTMAD^MR~123456789^^^PORTUGAL^SS||BAPTISTA^JOAO^A^JUNIOR
||19610615|M|||45^RUADOCARMO^^VILAREAL^VILAREAL^5000-678|GL||(259)123-456
||S||PATID12345001^2^M10^ADT1^AN^A|
PV1||I|UCI^01^02^ULSTMAD|||CIR-10^64^01|124340^SILVA^ANTONIO|856321^FERREIRA^CARLOS||ICU
|||||||856321^FERREIRA^CARLOS|S|||||||||||||||||||ULSTMAD|||||200707181123|</code></pre>
<p><code>EVN-2</code> (<code>200707190245</code>) records when the event was entered into the system; <code>EVN-6</code> (<code>200707190230</code>) records the actual transfer time. The 15-minute gap documents the administrative delay. In PV1: <code>PV1-3</code> = new location (<code>UCI^01^02</code>), <code>PV1-6</code> = previous location (<code>CIR-10^64^01</code>), <code>PV1-8</code> = Dr.&nbsp;Ferreira (new responsible), <code>PV1-10</code> = ICU service.</p>
</section>
<section id="adta03-discharge" class="level3" data-number="6.5.3">
<h3 data-number="6.5.3" class="anchored" data-anchor-id="adta03-discharge"><span class="header-section-number">6.5.3</span> ADT^A03 — Discharge</h3>
<p>The <code>A03</code> event records the end of the hospital stay. Field <code>PV1-36</code> indicates the discharge destination; fields <code>PV1-44</code> and <code>PV1-45</code> record the admission date and discharge date respectively <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<p>On 25 July 2007 at 10:00, João Baptista is discharged home with home health care (HH):</p>
<pre><code>MSH|^~\&amp;|ADT1|ULSTMAD|SCLINICO|ULSTMAD|200707251000||ADT^A03^ADT_A03|000003|P|2.8||||
EVN|A03|200707251000||01||200707251000
PID|1||PATID1234^^^ULSTMAD^MR~123456789^^^PORTUGAL^SS||BAPTISTA^JOAO^A^JUNIOR
||19610615|M|||45^RUADOCARMO^^VILAREAL^VILAREAL^5000-678|GL||(259)123-456
||S||PATID12345001^2^M10^ADT1^AN^A|
PV1||I|CIR-10^64^01||||124340^SILVA^ANTONIO|||SUR|||||||124340^SILVA^ANTONIO|S|1400|A
||||||||||||||||||HH|||ULSTMAD|||||200707181123|200707251000</code></pre>
<p><code>PV1-44</code> (<code>200707181123</code>) − <code>PV1-45</code> (<code>200707251000</code>) = 7-day hospital stay, automatically calculable by any receiving system. Possible values in <code>PV1-36</code> include: <code>HH</code> (home health care), <code>SNF</code> (skilled nursing facility), <code>HSP</code> (transfer to another hospital) and <code>EXP</code> (expired).</p>
<!--
  Diagram: ADT sequence A01 → A02 → A03 along a timeline.
-->
<div style="overflow-x:auto; margin:1.5rem 0;">
<svg viewbox="0 0 680 160" xmlns="http://www.w3.org/2000/svg" style="width:100%;max-width:680px;font-family:sans-serif;">
  <rect width="680" height="160" rx="10" fill="#f8fbfc"></rect>

  <!-- Timeline -->
  <line x1="60" y1="80" x2="620" y2="80" stroke="#cbd5e1" stroke-width="2"></line>

  <!-- Event 1: A01 -->
  <circle cx="140" cy="80" r="18" fill="#0a3d4a"></circle>
  <text x="140" y="85" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">A01</text>
  <text x="140" y="120" text-anchor="middle" font-size="10" font-weight="bold" fill="#0a3d4a">Admission</text>
  <text x="140" y="134" text-anchor="middle" font-size="9" fill="#64748b">18 Jul 11:23</text>
  <text x="140" y="148" text-anchor="middle" font-size="9" fill="#64748b">CIR-10 · Dr. Silva</text>

  <!-- Event 2: A02 -->
  <circle cx="340" cy="80" r="18" fill="#0d7c8c"></circle>
  <text x="340" y="85" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">A02</text>
  <text x="340" y="120" text-anchor="middle" font-size="10" font-weight="bold" fill="#0d7c8c">Transfer</text>
  <text x="340" y="134" text-anchor="middle" font-size="9" fill="#64748b">19 Jul 02:30</text>
  <text x="340" y="148" text-anchor="middle" font-size="9" fill="#64748b">ICU · Dr. Ferreira</text>

  <!-- Event 3: A03 -->
  <circle cx="560" cy="80" r="18" fill="#1ab3a6"></circle>
  <text x="560" y="85" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">A03</text>
  <text x="560" y="120" text-anchor="middle" font-size="10" font-weight="bold" fill="#1ab3a6">Discharge</text>
  <text x="560" y="134" text-anchor="middle" font-size="9" fill="#64748b">25 Jul 10:00</text>
  <text x="560" y="148" text-anchor="middle" font-size="9" fill="#64748b">Destination: HH</text>

  <!-- Duration -->
  <line x1="140" y1="55" x2="560" y2="55" stroke="#1ab3a6" stroke-width="1.5" stroke-dasharray="4" marker-start="url(#d1)" marker-end="url(#d2)"></line>
  <text x="350" y="46" text-anchor="middle" font-size="10" fill="#1ab3a6">7-day hospital stay</text>

  <defs>
    <marker id="d1" markerwidth="6" markerheight="6" refx="1" refy="3" orient="auto">
      <path d="M6,0 L0,3 L6,6 Z" fill="#1ab3a6"></path></marker>
    <marker id="d2" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#1ab3a6"></path></marker>
  </defs>
</svg>
</div>
<p>Figure 6.3 — ADT sequence for the João Baptista case: admission (A01), transfer (A02) and discharge (A03).</p>
</section>
</section>
<section id="sec-hl7v2-limitations" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="sec-hl7v2-limitations"><span class="header-section-number">6.6</span> HL7 v2 Limitations</h2>
<section id="structural-fragility-no-formal-schema" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="structural-fragility-no-formal-schema"><span class="header-section-number">6.6.1</span> Structural fragility: no formal schema</h3>
<p>HL7 v2 has no formal schema. Any string is accepted in any field — the standard does not define automatic format validation. Field <code>PID-7</code> (date of birth) should contain <code>YYYYMMDD</code>, but the receiver must accept whatever arrives. Format errors pass silently until they surface in a wrong clinical report <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<pre><code>PID|1||PAT001||SILVA^ANA||19850312|F|...    ← YYYYMMDD — correct
PID|1||PAT001||SILVA^ANA||1985-03-12|F|...  ← accepted, but different format
PID|1||PAT001||SILVA^ANA||12/03/1985|F|...  ← accepted, yet another dialect</code></pre>
<p>A database with a <code>DATE</code> column automatically rejects <code>15/06/1961</code>. In HL7 v2, no such mechanism exists. Each sending system has its own dialect for dates, genders and codes; the integration engine accumulates normalisation rules per system. As the hospital network grows, this normalisation work becomes a permanent ongoing cost.</p>
</section>
<section id="weak-semantics-local-value-tables" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="weak-semantics-local-value-tables"><span class="header-section-number">6.6.2</span> Weak semantics: local value tables</h3>
<p>HL7 v2 defines fields by name and position, but does not define the vocabulary of their values. The specification provides <strong>user-defined tables</strong>: each hospital chooses its own codes. What should be a shared vocabulary becomes a private dialect of each institution <span class="citation" data-cites="BensonGrieve2021">(<a href="../references.html#ref-BensonGrieve2021" role="doc-biblioref">Benson &amp; Grieve, 2021</a>)</span>.</p>
<p>The most common example is <code>PV1-4</code> (admission type):</p>
<div id="tbl-semantics" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-semantics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.7: Weak semantics: the same field, incompatible values across hospitals <span class="citation" data-cites="BensonGrieve2021">(<a href="../references.html#ref-BensonGrieve2021" role="doc-biblioref">Benson &amp; Grieve, 2021</a>)</span>.
</figcaption>
<div aria-describedby="tbl-semantics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Hospital</th>
<th>Value in PV1-4</th>
<th>Local meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hospital A</td>
<td><code>U</code></td>
<td>Urgência (Emergency)</td>
</tr>
<tr class="even">
<td>Hospital B</td>
<td><code>E</code></td>
<td>Emergency</td>
</tr>
<tr class="odd">
<td>Hospital C</td>
<td><code>1</code></td>
<td>Urgent</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>All three hospitals are conformant with the specification — and are incompatible with each other. The same problem exists in <code>PID-8</code> (gender), clinical service, diagnosis type and marital status: every field with a <em>user-defined table</em> is a potential point of incompatibility. Two “HL7 v2 conformant” systems may have completely different semantics and require bilateral mapping before any data exchange.</p>
</section>
<section id="z-segments-private-extensions" class="level3" data-number="6.6.3">
<h3 data-number="6.6.3" class="anchored" data-anchor-id="z-segments-private-extensions"><span class="header-section-number">6.6.3</span> Z-segments: private extensions</h3>
<p>Any segment whose identifier begins with <code>Z</code> is reserved for local use. The specification prohibits Z-segments in the normalised standard — they are intentionally private and opaque. Each hospital creates its own extra fields (e.g.&nbsp;<code>ZPI</code> for insurance information, <code>ZIN</code> for health subsystem data) without publishing them <span class="citation" data-cites="HL7_v28">(<a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.</p>
<p>The problem becomes apparent when integrating two hospitals:</p>
<pre><code>Hospital A:  ZIN|ADSE|GROUP001|PLANO_B
Hospital B:  ZSG|ADSE|PLANO_B|GROUP001</code></pre>
<p>The same content, different identifiers, different field order — mutually incompatible. An external parser does not know what <code>ZIN</code> or <code>ZSG</code> mean; it must be configured case by case, by bilateral agreement. Z-segments are the most visible example of a broader problem: the standard is open enough to generate incompatibilities even between conformant implementations.</p>
</section>
<section id="parsing-hidden-complexity" class="level3" data-number="6.6.4">
<h3 data-number="6.6.4" class="anchored" data-anchor-id="parsing-hidden-complexity"><span class="header-section-number">6.6.4</span> Parsing: hidden complexity</h3>
<p>Processing an HL7 v2 message is more demanding than simply splitting strings on the pipe character. Three main sources of complexity can be identified <span class="citation" data-cites="Bhagat2019">(<a href="../references.html#ref-Bhagat2019" role="doc-biblioref">Bhagat, 2019</a>)</span>:</p>
<ul>
<li><strong>Repeatable fields with <code>~</code></strong> — a field may have multiple values separated by tilde; <code>PID-3</code> can contain several identifiers for the same patient; the parser must handle lists, not single values.</li>
<li><strong>Opaque Z-segments</strong> — a generic parser does not know what <code>ZIN</code>, <code>ZPI</code> or <code>ZCU</code> mean; it must be configured case by case.</li>
<li><strong>Version differences</strong> — the same field may have different structures between v2.3 and v2.8; in a real environment, different systems send different versions and the parser must handle all of them.</li>
</ul>
<p>There is no universal parser for HL7 v2: every environment requires system-specific and version-specific rules.</p>
</section>
<section id="the-integration-engine-the-required-piece" class="level3" data-number="6.6.5">
<h3 data-number="6.6.5" class="anchored" data-anchor-id="the-integration-engine-the-required-piece"><span class="header-section-number">6.6.5</span> The integration engine: the required piece</h3>
<p>The limitations described above converge on one point: any real HL7 v2 environment requires an <strong>integration middleware</strong> — commonly called an <em>integration engine</em>. Products such as Mirth Connect, Rhapsody or InterSystems Ensemble receive messages from multiple systems, normalise formats, map local tables, translate Z-segments and route to the correct destinations <span class="citation" data-cites="BensonGrieve2021">(<a href="../references.html#ref-BensonGrieve2021" role="doc-biblioref">Benson &amp; Grieve, 2021</a>)</span>.</p>
<!--
  Diagram: integration engine — N sending systems → engine → N receiving systems.
-->
<div style="overflow-x:auto; margin:1.5rem 0;">
<svg viewbox="0 0 680 240" xmlns="http://www.w3.org/2000/svg" style="width:100%;max-width:680px;font-family:sans-serif;">
  <rect width="680" height="240" rx="10" fill="#f8fbfc"></rect>

  <!-- Sending systems (left) -->
  <rect x="15" y="30" width="110" height="32" rx="6" fill="#0a3d4a"></rect>
  <text x="70" y="51" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">HIS (Admissions)</text>
  <rect x="15" y="80" width="110" height="32" rx="6" fill="#0a3d4a"></rect>
  <text x="70" y="101" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">LIS (Laboratory)</text>
  <rect x="15" y="130" width="110" height="32" rx="6" fill="#0a3d4a"></rect>
  <text x="70" y="151" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">RIS (Radiology)</text>

  <!-- Arrows → engine -->
  <line x1="127" y1="46" x2="245" y2="100" stroke="#0d7c8c" stroke-width="1.5" marker-end="url(#ie1)"></line>
  <line x1="127" y1="96" x2="245" y2="110" stroke="#0d7c8c" stroke-width="1.5" marker-end="url(#ie1)"></line>
  <line x1="127" y1="146" x2="245" y2="120" stroke="#0d7c8c" stroke-width="1.5" marker-end="url(#ie1)"></line>

  <!-- Integration Engine -->
  <rect x="247" y="70" width="186" height="80" rx="10" fill="#0d7c8c"></rect>
  <text x="340" y="98" text-anchor="middle" font-size="12" font-weight="bold" fill="#fff">Integration Engine</text>
  <text x="340" y="115" text-anchor="middle" font-size="9" fill="#e2f4f3">Mirth · Rhapsody · Ensemble</text>
  <text x="340" y="130" text-anchor="middle" font-size="9" fill="#e2f4f3">Normalises · Maps · Routes</text>

  <!-- Arrows engine → receivers -->
  <line x1="435" y1="100" x2="548" y2="50" stroke="#1ab3a6" stroke-width="1.5" marker-end="url(#ie2)"></line>
  <line x1="435" y1="110" x2="548" y2="100" stroke="#1ab3a6" stroke-width="1.5" marker-end="url(#ie2)"></line>
  <line x1="435" y1="120" x2="548" y2="150" stroke="#1ab3a6" stroke-width="1.5" marker-end="url(#ie2)"></line>

  <!-- Receiving systems (right) -->
  <rect x="550" y="30" width="110" height="32" rx="6" fill="#1ab3a6"></rect>
  <text x="605" y="51" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">EMR (Clinical)</text>
  <rect x="550" y="82" width="110" height="32" rx="6" fill="#1ab3a6"></rect>
  <text x="605" y="103" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">Pharmacy</text>
  <rect x="550" y="134" width="110" height="32" rx="6" fill="#1ab3a6"></rect>
  <text x="605" y="155" text-anchor="middle" font-size="10" font-weight="bold" fill="#fff">PACS (Imaging)</text>

  <text x="340" y="225" text-anchor="middle" font-size="14" fill="#64748b">
    Figure 6.4 — Integration engine: the required piece in any real HL7 v2 environment
  </text>

  <defs>
    <marker id="ie1" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#0d7c8c"></path></marker>
    <marker id="ie2" markerwidth="6" markerheight="6" refx="5" refy="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#1ab3a6"></path></marker>
  </defs>
</svg>
</div>
<p>The integration engine is not optional: it is the piece that makes HL7 v2 work in heterogeneous environments. The cost the standard does not show is the maintenance cost of this middleware: each new system joining the network requires analysis, mapping and testing. As N systems grow, the number of interfaces — and the cost of maintaining them — grows with it. This is the structural limit of the bilateral model that HL7 v2 imposes.</p>
</section>
<section id="balance-what-hl7-v2-solved-and-where-it-fell-short" class="level3" data-number="6.6.6">
<h3 data-number="6.6.6" class="anchored" data-anchor-id="balance-what-hl7-v2-solved-and-where-it-fell-short"><span class="header-section-number">6.6.6</span> Balance: what HL7 v2 solved and where it fell short</h3>
<p>HL7 v2 solved a real problem: it eliminated the manual exchange of data between hospital systems, created a trigger-event model aligned with clinical workflows, and survived 35 years of technological change. Its limits only became apparent as scale grew.</p>
<div id="tbl-balance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-balance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.8: Balance of HL7 v2 <span class="citation" data-cites="HL7_v28 BensonGrieve2021">(<a href="../references.html#ref-BensonGrieve2021" role="doc-biblioref">Benson &amp; Grieve, 2021</a>; <a href="../references.html#ref-HL7_v28" role="doc-biblioref">HL7 International, 2014</a>)</span>.
</figcaption>
<div aria-describedby="tbl-balance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Aspect</th>
<th>Assessment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Elimination of manual data exchange</td>
<td>Solved</td>
</tr>
<tr class="even">
<td>Trigger-event model aligned with clinical workflows</td>
<td>Solved</td>
</tr>
<tr class="odd">
<td>Global adoption (95% of hospitals)</td>
<td>Solved</td>
</tr>
<tr class="even">
<td>Mature ecosystem of tools</td>
<td>Solved</td>
</tr>
<tr class="odd">
<td>Formal schema with automatic validation</td>
<td>Not solved</td>
</tr>
<tr class="even">
<td>Shared semantics across institutions</td>
<td>Not solved</td>
</tr>
<tr class="odd">
<td>Interoperable private extensions (Z-segments)</td>
<td>Not solved</td>
</tr>
<tr class="even">
<td>Universal parser</td>
<td>Not solved</td>
</tr>
<tr class="odd">
<td>Integration cost proportional to number of systems</td>
<td>Not solved</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="sec-hl7v2-summary" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="sec-hl7v2-summary"><span class="header-section-number">6.7</span> Summary and Exercises</h2>
<section id="consolidation-exercises" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="consolidation-exercises">Consolidation exercises</h3>
<ol type="1">
<li><p>A laboratory system (LIS) receives an order sent by the prescribing system. Identify: (a) the HL7 message type used; (b) the trigger event; (c) the MSH fields that allow the LIS to determine who sent the order and which HL7 version it conforms to.</p></li>
<li><p>The <code>PID-3</code> field of a message contains the value <code>PATID1234^^^ULSTMAD^MR~123456789^^^PORTUGAL^SS</code>. Explain the role of the <code>~</code> character in this context and identify the two identifiers present, stating the type of each.</p></li>
<li><p>A negative ACK (AE) contains <code>ERR||PID^5|101^Required field missing|E</code>. Interpret each component of this segment and explain the practical consequence for the sending system.</p></li>
<li><p>Two hospitals use different values in <code>PV1-4</code> to classify emergency admissions: Hospital X uses <code>U</code>, Hospital Y uses <code>E</code>. Both claim to be HL7 v2 conformant. Explain how this situation is possible and what architectural component is needed to integrate them.</p></li>
<li><p>A hospital needs to transmit health insurance data (subsystem code, group number, plan) between the HIS and the pharmacy. The HL7 v2 specification defines no standard segment for this purpose. What mechanism does the standard provide? What are the implications for interoperability with other hospitals?</p></li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-BensonGrieve2021" class="csl-entry" role="listitem">
Benson, T., &amp; Grieve, G. (2021). <em>Principles of health interoperability: <span>FHIR</span>, <span>HL7</span> and <span>SNOMED CT</span></em> (4th ed.). Springer. <a href="https://doi.org/10.1007/978-3-030-56883-2">https://doi.org/10.1007/978-3-030-56883-2</a>
</div>
<div id="ref-Bhagat2019" class="csl-entry" role="listitem">
Bhagat, R. (2019). <em><span>HL7</span> for busy professionals</em>. Anchiove.
</div>
<div id="ref-HL7_v28" class="csl-entry" role="listitem">
HL7 International. (2014). <em><span>HL7</span> messaging standard version 2.8</em>. <a href="https://www.hl7.org/implement/standards/product_brief.cfm?product_id=185" class="uri">https://www.hl7.org/implement/standards/product_brief.cfm?product_id=185</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../capitulos/cap05.html" class="pagination-link" aria-label="DICOM Services and PACS Architecture">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">DICOM Services and PACS Architecture</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../references.html" class="pagination-link" aria-label="References">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Medical Informatics — Master’s in Biomedical Engineering · UTAD</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://joaoagostinhopavao.github.io/sebenta-im/">🇵🇹 Português</a></p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>